//! Decimal contract validation — Phase 1 (proof of concept).
//!
//! Grades gMath's decimal domain against an mpmath oracle under gMath's OWN
//! declared rounding rule (round-half-away-from-zero), and separately counts
//! where that disagrees with banker's rounding (HalfToEven) — the
//! financial-rounding gap that motivates a future `_with(RoundingMode)` path.
//!
//! Arm A: the imperative `DecimalFixed<SCALE>` surface (deterministic scale,
//! direct `raw_value()` extraction). The canonical `gmath()` surface shares the
//! engine but materializes at a different scale and gets its own arm later
//! (see tests/oracle_golden/DESIGN.md).
//!
//! Oracle format (adopted from mootable/decimal-scaled, independently
//! generated by scripts/gen_decimal_golden.py): each line is
//! `<input_raw>\t<floor_raw>\t<cls>`, mode-agnostic. The correctly-rounded
//! result under any mode is `floor_raw` or `floor_raw+1`, derived from
//! `(floor, cls, sign, mode)`.
//!
//! Balanced profile only: `DecimalFixed<28>` needs a compute dp wider than 28
//! for guard digits (balanced = 77). Run with:
//!   rm -rf target/debug/incremental/
//!   GMATH_PROFILE=balanced cargo test --test decimal_contract_validation -- --nocapture
#![cfg(table_format = "q128_128")]

use g_math::fixed_point::DecimalFixed;
use std::path::PathBuf;

/// Storage scale of the fixtures. Lands on decimal-scaled's d38_s28 grid point.
const SCALE: u8 = 28;

/// Max |delta| (in storage LSB) we accept before calling it a contract
/// violation. gMath's wide-tier strategy targets correctly-rounded; 1 LSB
/// covers the double-rounding window. Anything beyond is a real bug.
const TOL_LSB: i128 = 1;

/// Fractional class of `f(x)*10^scale - floor` in [0,1).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Cls {
    Exact, // Z
    Low,   // L  (0 < frac < 0.5)
    Tie,   // E  (frac == 0.5)
    High,  // G  (0.5 < frac < 1)
}

impl Cls {
    fn parse(s: &str) -> Cls {
        match s {
            "Z" => Cls::Exact,
            "L" => Cls::Low,
            "E" => Cls::Tie,
            "G" => Cls::High,
            other => panic!("unknown class column: {other:?}"),
        }
    }
}

#[derive(Clone, Copy)]
enum Mode {
    HalfAwayFromZero, // gMath decimal's declared rule
    HalfToEven,       // banker's rounding (decimal-scaled default; financial)
}

/// Correctly-rounded storage integer from `(floor, cls)` under `mode`.
/// Mirrors decimal-scaled's grader for the two half-modes we need; the
/// directed modes (Floor/Ceiling/Trunc) are not exercised yet.
fn oracle_correctly_rounded(floor: i128, cls: Cls, mode: Mode) -> i128 {
    match cls {
        Cls::Exact => floor,
        // For both half-modes, nearest is floor (L) or floor+1 (G) regardless
        // of sign — ties never enter here.
        Cls::Low => floor,
        Cls::High => floor + 1,
        Cls::Tie => match mode {
            // Away-from-zero: bump iff the true value is non-negative.
            // floor toward -inf, so the true value is < 0 exactly when floor < 0.
            Mode::HalfAwayFromZero => {
                if floor >= 0 {
                    floor + 1
                } else {
                    floor
                }
            }
            // Banker's: pick the even neighbour (last decimal digit parity ==
            // integer parity, since 10 is even).
            Mode::HalfToEven => {
                if floor.rem_euclid(2) == 0 {
                    floor
                } else {
                    floor + 1
                }
            }
        },
    }
}

struct GoldenLine {
    input: i128,
    floor: i128,
    cls: Cls,
}

fn load(func: &str) -> Vec<GoldenLine> {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests/oracle_golden");
    path.push(format!("{func}_s{SCALE}.txt"));
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let cols: Vec<&str> = line.split('\t').collect();
        assert_eq!(cols.len(), 3, "unary golden line must have 3 columns: {line:?}");
        out.push(GoldenLine {
            input: cols[0].parse().expect("input_raw i128"),
            floor: cols[1].parse().expect("floor_raw i128"),
            cls: Cls::parse(cols[2]),
        });
    }
    assert!(!out.is_empty(), "no golden lines for {func}");
    out
}

#[derive(Default)]
struct Report {
    n: usize,
    correctly_rounded: usize, // delta == 0 under HalfAwayFromZero
    within_tol: usize,        // 0 < delta <= TOL_LSB
    violations: usize,        // delta > TOL_LSB
    max_delta: i128,
    ties: usize,              // E-class inputs (counted separately)
    tie_divergences: usize,   // half-away vs half-even disagree (financial gap)
    worst_input: i128,
}

/// Run one function: `compute` maps a constructed DecimalFixed to its raw
/// result integer at SCALE.
fn run(func: &str, compute: impl Fn(DecimalFixed<28>) -> i128) -> Report {
    let mut r = Report::default();
    for g in load(func) {
        r.n += 1;
        let actual = compute(DecimalFixed::<28>::from_raw(g.input));
        let expected = oracle_correctly_rounded(g.floor, g.cls, Mode::HalfAwayFromZero);
        let even = oracle_correctly_rounded(g.floor, g.cls, Mode::HalfToEven);
        if expected != even {
            r.tie_divergences += 1;
        }
        if g.cls == Cls::Tie {
            r.ties += 1;
        }
        let delta = (actual - expected).abs();
        if delta == 0 {
            r.correctly_rounded += 1;
        } else if delta <= TOL_LSB {
            r.within_tol += 1;
        } else {
            r.violations += 1;
        }
        if delta > r.max_delta {
            r.max_delta = delta;
            r.worst_input = g.input;
        }
    }
    r
}

fn report_and_assert(func: &str, r: &Report) {
    eprintln!(
        "[decimal/{func}] n={} correct={} within_tol(<= {})={} violations={} \
         max_delta={} ties(E)={} financial_gap(away!=even)={}{}",
        r.n,
        r.correctly_rounded,
        TOL_LSB,
        r.within_tol,
        r.violations,
        r.max_delta,
        r.ties,
        r.tie_divergences,
        if r.violations > 0 {
            format!(" worst_input={}", r.worst_input)
        } else {
            String::new()
        },
    );
    assert_eq!(
        r.violations, 0,
        "{func}: {} contract violations (max_delta={} LSB > tol {}), worst input_raw={}",
        r.violations, r.max_delta, TOL_LSB, r.worst_input
    );
}

#[test]
fn decimal_exp_contract() {
    let r = run("exp", |d| d.exp().raw_value());
    report_and_assert("exp", &r);
}

#[test]
fn decimal_ln_contract() {
    let r = run("ln", |d| d.ln().raw_value());
    report_and_assert("ln", &r);
}

#[test]
fn decimal_sqrt_contract() {
    let r = run("sqrt", |d| d.sqrt().raw_value());
    report_and_assert("sqrt", &r);
}

#[test]
fn decimal_sin_contract() {
    let r = run("sin", |d| d.sin().raw_value());
    report_and_assert("sin", &r);
}

/// Pin the grader against decimal-scaled's rule for every (cls, mode, sign).
/// This proves the grader independently of whether the fixtures contain ties.
#[test]
fn grader_truth_table() {
    use Cls::*;
    use Mode::*;
    // (floor, cls, mode, expected)
    let cases: &[(i128, Cls, Mode, i128)] = &[
        // Exact: every mode returns floor.
        (10, Exact, HalfAwayFromZero, 10),
        (-10, Exact, HalfToEven, -10),
        // Low: nearest is floor.
        (10, Low, HalfAwayFromZero, 10),
        (-10, Low, HalfToEven, -10),
        // High: nearest is floor+1.
        (10, High, HalfAwayFromZero, 11),
        (-10, High, HalfToEven, -9),
        // Tie, away-from-zero: positive bumps up, negative stays (more |.|).
        (2, Tie, HalfAwayFromZero, 3),    // +2.5 -> 3
        (-3, Tie, HalfAwayFromZero, -3),  // -2.5 -> -3 (floor toward -inf is -3)
        // Tie, half-even: pick even neighbour.
        (2, Tie, HalfToEven, 2),   // 2 even -> 2
        (3, Tie, HalfToEven, 4),   // 3 odd  -> 4
        (-3, Tie, HalfToEven, -2), // -3 odd -> -2 (even)
        (-4, Tie, HalfToEven, -4), // -4 even -> -4
    ];
    for &(floor, cls, mode, want) in cases {
        let got = oracle_correctly_rounded(floor, cls, mode);
        assert_eq!(got, want, "grader({floor}, {cls:?}, mode) = {got}, want {want}");
    }
}
