//! Decimal contract validation — Phase 1 (proof of concept).
//!
//! Grades gMath's decimal domain against an mpmath oracle under gMath's OWN
//! declared rounding rule (round-half-away-from-zero), and separately counts
//! where that disagrees with banker's rounding (HalfToEven) — the
//! financial-rounding gap that motivates a future `_with(RoundingMode)` path.
//!
//! Arm A: the imperative `DecimalFixed<SCALE>` surface (deterministic scale,
//! direct `raw_value()` extraction). The canonical `gmath()` surface shares the
//! engine but materializes at a different scale and gets its own arm later
//! (see tests/oracle_golden/DESIGN.md).
//!
//! Oracle format (adopted from mootable/decimal-scaled, independently
//! generated by scripts/gen_decimal_golden.py): each line is
//! `<input_raw>\t<floor_raw>\t<cls>`, mode-agnostic. The correctly-rounded
//! result under any mode is `floor_raw` or `floor_raw+1`, derived from
//! `(floor, cls, sign, mode)`.
//!
//! Balanced profile only: `DecimalFixed<28>` needs a compute dp wider than 28
//! for guard digits (balanced = 77). Run with:
//!   rm -rf target/debug/incremental/
//!   GMATH_PROFILE=balanced cargo test --test decimal_contract_validation -- --nocapture
#![cfg(table_format = "q128_128")]

use g_math::fixed_point::DecimalFixed;
use std::path::PathBuf;

/// Storage scale of the fixtures. Lands on decimal-scaled's d38_s28 grid point.
const SCALE: u8 = 28;

/// Max |delta| (in storage LSB) we accept before calling it a contract
/// violation. gMath's wide-tier strategy targets correctly-rounded; 1 LSB
/// covers the double-rounding window. Anything beyond is a real bug.
const TOL_LSB: i128 = 1;

/// Fractional class of `f(x)*10^scale - floor` in [0,1).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Cls {
    Exact, // Z
    Low,   // L  (0 < frac < 0.5)
    Tie,   // E  (frac == 0.5)
    High,  // G  (0.5 < frac < 1)
}

impl Cls {
    fn parse(s: &str) -> Cls {
        match s {
            "Z" => Cls::Exact,
            "L" => Cls::Low,
            "E" => Cls::Tie,
            "G" => Cls::High,
            other => panic!("unknown class column: {other:?}"),
        }
    }
}

#[derive(Clone, Copy)]
enum Mode {
    HalfAwayFromZero, // gMath decimal's declared rule
    HalfToEven,       // banker's rounding (decimal-scaled default; financial)
}

/// Correctly-rounded storage integer from `(floor, cls)` under `mode`.
/// Mirrors decimal-scaled's grader for the two half-modes we need; the
/// directed modes (Floor/Ceiling/Trunc) are not exercised yet.
fn oracle_correctly_rounded(floor: i128, cls: Cls, mode: Mode) -> i128 {
    match cls {
        Cls::Exact => floor,
        // For both half-modes, nearest is floor (L) or floor+1 (G) regardless
        // of sign — ties never enter here.
        Cls::Low => floor,
        Cls::High => floor + 1,
        Cls::Tie => match mode {
            // Away-from-zero: bump iff the true value is non-negative.
            // floor toward -inf, so the true value is < 0 exactly when floor < 0.
            Mode::HalfAwayFromZero => {
                if floor >= 0 {
                    floor + 1
                } else {
                    floor
                }
            }
            // Banker's: pick the even neighbour (last decimal digit parity ==
            // integer parity, since 10 is even).
            Mode::HalfToEven => {
                if floor.rem_euclid(2) == 0 {
                    floor
                } else {
                    floor + 1
                }
            }
        },
    }
}

struct GoldenLine {
    input: i128,
    floor: i128,
    cls: Cls,
}

fn load(func: &str) -> Vec<GoldenLine> {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests/oracle_golden");
    path.push(format!("{func}_s{SCALE}.txt"));
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let cols: Vec<&str> = line.split('\t').collect();
        assert_eq!(cols.len(), 3, "unary golden line must have 3 columns: {line:?}");
        out.push(GoldenLine {
            input: cols[0].parse().expect("input_raw i128"),
            floor: cols[1].parse().expect("floor_raw i128"),
            cls: Cls::parse(cols[2]),
        });
    }
    assert!(!out.is_empty(), "no golden lines for {func}");
    out
}

#[derive(Default)]
struct Report {
    n: usize,
    correctly_rounded: usize, // delta == 0 under HalfAwayFromZero
    within_tol: usize,        // 0 < delta <= TOL_LSB
    violations: usize,        // delta > TOL_LSB
    max_delta: i128,
    ties: usize,              // E-class inputs (counted separately)
    tie_divergences: usize,   // half-away vs half-even disagree (financial gap)
    worst_input: i128,
}

/// Run one function: `compute` maps a constructed DecimalFixed to its raw
/// result integer at SCALE.
fn run(func: &str, compute: impl Fn(DecimalFixed<28>) -> i128) -> Report {
    let mut r = Report::default();
    for g in load(func) {
        r.n += 1;
        let actual = compute(DecimalFixed::<28>::from_raw(g.input));
        let expected = oracle_correctly_rounded(g.floor, g.cls, Mode::HalfAwayFromZero);
        let even = oracle_correctly_rounded(g.floor, g.cls, Mode::HalfToEven);
        if expected != even {
            r.tie_divergences += 1;
        }
        if g.cls == Cls::Tie {
            r.ties += 1;
        }
        let delta = (actual - expected).abs();
        if delta == 0 {
            r.correctly_rounded += 1;
        } else if delta <= TOL_LSB {
            r.within_tol += 1;
        } else {
            r.violations += 1;
        }
        if delta > r.max_delta {
            r.max_delta = delta;
            r.worst_input = g.input;
        }
    }
    r
}

fn report_and_assert(func: &str, r: &Report) {
    eprintln!(
        "[decimal/{func}] n={} correct={} within_tol(<= {})={} violations={} \
         max_delta={} ties(E)={} financial_gap(away!=even)={}{}",
        r.n,
        r.correctly_rounded,
        TOL_LSB,
        r.within_tol,
        r.violations,
        r.max_delta,
        r.ties,
        r.tie_divergences,
        if r.violations > 0 {
            format!(" worst_input={}", r.worst_input)
        } else {
            String::new()
        },
    );
    assert_eq!(
        r.violations, 0,
        "{func}: {} contract violations (max_delta={} LSB > tol {}), worst input_raw={}",
        r.violations, r.max_delta, TOL_LSB, r.worst_input
    );
}

#[test]
fn decimal_exp_contract() {
    let r = run("exp", |d| d.exp().raw_value());
    report_and_assert("exp", &r);
}

#[test]
fn decimal_ln_contract() {
    let r = run("ln", |d| d.ln().raw_value());
    report_and_assert("ln", &r);
}

#[test]
fn decimal_sqrt_contract() {
    let r = run("sqrt", |d| d.sqrt().raw_value());
    report_and_assert("sqrt", &r);
}

#[test]
fn decimal_sin_contract() {
    let r = run("sin", |d| d.sin().raw_value());
    report_and_assert("sin", &r);
}

// ============================================================================
// Oracle #2 — adversarial grading against mootable/decimal-scaled's corpus.
//
// Env-gated: set GMATH_DECIMAL_SCALED_GOLDEN to a local clone of decimal-scaled
// (pinned to e6c7497). Self-skips if unset, so normal runs/CI are unaffected.
// This is the INDEPENDENT, adversarial oracle (tie-hunting, overflow edges,
// large-trig). Report-mode in this first pass: it surveys the full error
// distribution rather than enforcing a tolerance we have not measured yet.
// It DOES hard-assert zero panics on valid-domain inputs — a panic there is a
// bug, not a tolerance question.
//
// Run (single-threaded so the panic-hook swap doesn't race):
//   GMATH_DECIMAL_SCALED_GOLDEN=~/gh/decimal-scaled GMATH_PROFILE=balanced \
//     cargo test --test decimal_contract_validation oracle2 -- --nocapture --test-threads=1
// ============================================================================

fn oracle2_dir() -> Option<PathBuf> {
    std::env::var_os("GMATH_DECIMAL_SCALED_GOLDEN").map(PathBuf::from)
}

fn parse_unary_file(path: &std::path::Path) -> Vec<GoldenLine> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let cols: Vec<&str> = line.split('\t').collect();
        if cols.len() != 3 {
            continue; // defensively skip non-unary rows
        }
        let (Ok(input), Ok(floor)) = (cols[0].parse::<i128>(), cols[1].parse::<i128>()) else {
            continue; // wider-than-i128 floor (shouldn't happen at d38) -> skip
        };
        out.push(GoldenLine { input, floor, cls: Cls::parse(cols[2]) });
    }
    out
}

#[derive(Default)]
struct O2 {
    n: usize,
    exact: usize,   // delta 0  (correctly rounded)
    one: usize,     // delta 1  (double-rounding window)
    small: usize,   // delta 2..=8
    large: usize,   // delta > 8 (suspicious — real weakness)
    skipped_domain: usize,
    skipped_range: usize,
    errored: usize, // gMath panicked (overflow / unexpected)
    max_delta: i128,
    worst_input: i128,
    ties: usize,
    financial_gap: usize,
}

fn run_oracle2(
    func: &str,
    in_domain: impl Fn(i128) -> bool,
    compute: impl Fn(DecimalFixed<28>) -> i128,
) -> Option<O2> {
    let dir = oracle2_dir()?;
    let path = dir.join("tests/golden").join(format!("{func}_d38_s{SCALE}.txt"));
    if !path.exists() {
        eprintln!("[oracle2/{func}] SKIP — {} not found", path.display());
        return Some(O2::default());
    }
    let lines = parse_unary_file(&path);
    let mut r = O2::default();
    // Silence .expect() panic spew; we count panics as `errored` instead.
    let prev_hook = std::panic::take_hook();
    std::panic::set_hook(Box::new(|_| {}));
    for g in &lines {
        if !in_domain(g.input) {
            r.skipped_domain += 1;
            continue;
        }
        if g.floor.checked_abs().map_or(true, |a| a > i128::MAX / 2) {
            r.skipped_range += 1;
            continue;
        }
        r.n += 1;
        if g.cls == Cls::Tie {
            r.ties += 1;
        }
        let expected = oracle_correctly_rounded(g.floor, g.cls, Mode::HalfAwayFromZero);
        if expected != oracle_correctly_rounded(g.floor, g.cls, Mode::HalfToEven) {
            r.financial_gap += 1;
        }
        let computed = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            compute(DecimalFixed::<28>::from_raw(g.input))
        }));
        let actual = match computed {
            Ok(v) => v,
            Err(_) => {
                r.errored += 1;
                continue;
            }
        };
        let delta = (actual - expected).abs();
        match delta {
            0 => r.exact += 1,
            1 => r.one += 1,
            2..=8 => r.small += 1,
            _ => r.large += 1,
        }
        if delta > r.max_delta {
            r.max_delta = delta;
            r.worst_input = g.input;
        }
    }
    std::panic::set_hook(prev_hook);
    Some(r)
}

fn report_o2(func: &str, r: &O2) {
    eprintln!(
        "[oracle2/{func}] n={} exact={} 1LSB={} 2-8={} >8={} max_delta={} \
         errored={} skip_domain={} skip_range={} ties(E)={} fin_gap={}{}",
        r.n, r.exact, r.one, r.small, r.large, r.max_delta, r.errored,
        r.skipped_domain, r.skipped_range, r.ties, r.financial_gap,
        if r.max_delta > 1 {
            format!(" worst_input={}", r.worst_input)
        } else {
            String::new()
        },
    );
    assert_eq!(r.errored, 0, "{func}: {} panics on valid-domain inputs", r.errored);
}

#[test]
fn oracle2_exp() {
    if let Some(r) = run_oracle2("exp", |_| true, |d| d.exp().raw_value()) {
        report_o2("exp", &r);
    }
}

#[test]
fn oracle2_ln() {
    if let Some(r) = run_oracle2("ln", |x| x > 0, |d| d.ln().raw_value()) {
        report_o2("ln", &r);
    }
}

#[test]
fn oracle2_sqrt() {
    if let Some(r) = run_oracle2("sqrt", |x| x >= 0, |d| d.sqrt().raw_value()) {
        report_o2("sqrt", &r);
    }
}

#[test]
fn oracle2_sin() {
    if let Some(r) = run_oracle2("sin", |_| true, |d| d.sin().raw_value()) {
        report_o2("sin", &r);
    }
}

/// Pin the grader against decimal-scaled's rule for every (cls, mode, sign).
/// This proves the grader independently of whether the fixtures contain ties.
#[test]
fn grader_truth_table() {
    use Cls::*;
    use Mode::*;
    // (floor, cls, mode, expected)
    let cases: &[(i128, Cls, Mode, i128)] = &[
        // Exact: every mode returns floor.
        (10, Exact, HalfAwayFromZero, 10),
        (-10, Exact, HalfToEven, -10),
        // Low: nearest is floor.
        (10, Low, HalfAwayFromZero, 10),
        (-10, Low, HalfToEven, -10),
        // High: nearest is floor+1.
        (10, High, HalfAwayFromZero, 11),
        (-10, High, HalfToEven, -9),
        // Tie, away-from-zero: positive bumps up, negative stays (more |.|).
        (2, Tie, HalfAwayFromZero, 3),    // +2.5 -> 3
        (-3, Tie, HalfAwayFromZero, -3),  // -2.5 -> -3 (floor toward -inf is -3)
        // Tie, half-even: pick even neighbour.
        (2, Tie, HalfToEven, 2),   // 2 even -> 2
        (3, Tie, HalfToEven, 4),   // 3 odd  -> 4
        (-3, Tie, HalfToEven, -2), // -3 odd -> -2 (even)
        (-4, Tie, HalfToEven, -4), // -4 even -> -4
    ];
    for &(floor, cls, mode, want) in cases {
        let got = oracle_correctly_rounded(floor, cls, mode);
        assert_eq!(got, want, "grader({floor}, {cls:?}, mode) = {got}, want {want}");
    }
}
