//! Decimal Transcendental ULP Validation — mpmath-verified test suite.
//!
//! Tests all decimal transcendental engines against mpmath-generated reference values
//! across ~3200 points per profile, covering:
//!   - **Edge cases**: domain boundaries, near-zero, ±1, ±π/4, ±π/2, ±π
//!   - **Adversarial inputs**: near-singular (tan near π/2, ln near 0, acosh near 1)
//!   - **Near-boundary**: asin/acos near ±1, atanh near ±1, acosh just above 1
//!   - **Financial stress**: small interest rates (0.001-0.2), 1 + r/n where r small
//!   - **Full domain sweeps**: uniform and log-spaced grids
//!
//! Reference data generated by: `scripts/generate_decimal_transcendental_refs.py`
//! (uses mpmath at 300 decimal places, writes scaled integers at profile compute dp)
//!
//! # Running
//!
//! ```bash
//! GMATH_PROFILE=realtime   cargo test --test decimal_transcendental_validation -- --nocapture
//! GMATH_PROFILE=compact    cargo test --test decimal_transcendental_validation -- --nocapture
//! GMATH_PROFILE=embedded   cargo test --test decimal_transcendental_validation -- --nocapture
//! GMATH_PROFILE=balanced   cargo test --test decimal_transcendental_validation -- --nocapture
//! GMATH_PROFILE=scientific cargo test --test decimal_transcendental_validation -- --nocapture
//! ```
//!
//! # ULP semantics
//!
//! All references are scaled integers at the profile's `DECIMAL_COMPUTE_DP`, so
//! ULP = `|actual_int - expected_int|`. One ULP equals `10^-compute_dp` in actual value.

#[allow(unused_imports)]
use std::time::Instant;

// ════════════════════════════════════════════════════════════════════
// Shared ULP stats tracker
// ════════════════════════════════════════════════════════════════════

#[allow(dead_code)]
struct UlpStats {
    name: &'static str,
    max_ulp: u128,
    sum_ulp: u128,
    count: usize,
    worst_label: String,
    errors: usize,
    ulps: Vec<u128>,
}

#[allow(dead_code)]
impl UlpStats {
    fn new(name: &'static str) -> Self {
        Self {
            name,
            max_ulp: 0,
            sum_ulp: 0,
            count: 0,
            worst_label: String::new(),
            errors: 0,
            ulps: Vec::new(),
        }
    }

    fn record(&mut self, ulp: u128, label: &str) {
        self.ulps.push(ulp);
        self.sum_ulp = self.sum_ulp.saturating_add(ulp);
        self.count += 1;
        if ulp > self.max_ulp {
            self.max_ulp = ulp;
            self.worst_label = label.to_string();
        }
    }

    fn record_error(&mut self, label: &str) {
        self.errors += 1;
        if self.errors <= 5 {
            eprintln!("  DECIMAL {} eval error: {}", self.name, label);
        }
    }

    fn p99(&self) -> u128 {
        if self.ulps.is_empty() { return 0; }
        let mut sorted = self.ulps.clone();
        sorted.sort();
        let idx = (sorted.len() as f64 * 0.99).ceil() as usize;
        sorted[idx.min(sorted.len() - 1)]
    }

    fn mean(&self) -> f64 {
        if self.count == 0 { return 0.0; }
        self.sum_ulp as f64 / self.count as f64
    }

    fn report(&self, profile: &str, compute_dp: u32) {
        eprintln!(
            "DECIMAL {:6} {}: max={:<6} mean={:<8.1} p99={:<6} points={:<5} dp={} (worst: {}){}",
            self.name, profile, self.max_ulp, self.mean(), self.p99(),
            self.count, compute_dp, self.worst_label,
            if self.errors > 0 { format!(" [{} errors]", self.errors) } else { String::new() }
        );
    }

    fn report_throughput(&self, profile: &str, storage_dp: u32, elapsed: std::time::Duration) {
        let total_ns = elapsed.as_nanos() as f64;
        let per_call_ns = if self.count > 0 { total_ns / self.count as f64 } else { 0.0 };
        let ops_per_sec = if total_ns > 0.0 { self.count as f64 / (total_ns / 1e9) } else { 0.0 };
        let (throughput_val, throughput_unit) = if ops_per_sec >= 1_000_000.0 {
            (ops_per_sec / 1_000_000.0, "M ops/s")
        } else if ops_per_sec >= 1_000.0 {
            (ops_per_sec / 1_000.0, "K ops/s")
        } else {
            (ops_per_sec, "  ops/s")
        };
        eprintln!(
            "DECIMAL {:6} {}: max={:<4} p99={:<4} dp={:<3} | {:>8.0}ns/op  {:>6.1} {} | points={}{}",
            self.name, profile, self.max_ulp, self.p99(), storage_dp,
            per_call_ns, throughput_val, throughput_unit, self.count,
            if self.errors > 0 { format!(" [{} errors]", self.errors) } else { String::new() }
        );
    }
}

// ════════════════════════════════════════════════════════════════════
// Q16.16 Profile — realtime (compute_dp = 9, i64)
// ════════════════════════════════════════════════════════════════════

#[cfg(table_format = "q16_16")]
mod q16_16 {
    use super::*;
    use g_math::fixed_point::domains::decimal_fixed::transcendental::{
        decimal_exp, decimal_ln, decimal_sqrt, decimal_sin, decimal_cos, decimal_atan,
        decimal_atan2,
    };

    include!("data/decimal_refs_q16_16.rs");
    const COMPUTE_DP: u32 = 9;
    const PROFILE: &str = "Q16.16";

    fn ulp_i64(actual: i64, expected: i64) -> u128 {
        (actual as i128 - expected as i128).unsigned_abs()
    }

    /// Downscale i64 value at compute_dp=9 to target_dp with round-half-up.
    fn downscale_to_dp(v: i64, target_dp: u32) -> i64 {
        if target_dp >= 9 { return v; }
        let diff = 9 - target_dp;
        let divisor = 10i64.pow(diff);
        let half = divisor / 2;
        let rounded = if v < 0 { v - half } else { v + half };
        rounded / divisor
    }

    macro_rules! storage_ulp_test {
        ($name:ident, $fn:ident, $refs:ident, $storage_dp:expr, $max_ulp:expr) => {
            #[test]
            fn $name() {
                let mut stats = UlpStats::new(stringify!($fn));
                // Warmup: prime caches and thread-local state
                if let Some(&(input, _, _)) = $refs.first() {
                    let _ = $fn(input);
                }
                // Run N passes to get stable timing
                const PASSES: usize = 8;
                let start = std::time::Instant::now();
                for _ in 0..PASSES {
                    for &(input, expected, label) in $refs.iter() {
                        match $fn(input) {
                            Ok(actual) => {
                                let actual_s = downscale_to_dp(actual, $storage_dp);
                                let expected_s = downscale_to_dp(expected, $storage_dp);
                                stats.record(ulp_i64(actual_s, expected_s), label);
                            }
                            Err(_) => stats.record_error(label),
                        }
                    }
                }
                let elapsed = start.elapsed();
                stats.report_throughput(PROFILE, $storage_dp, elapsed);
                assert!(stats.max_ulp <= $max_ulp,
                    "{} {} (storage dp={}) max ULP {} > {} (worst: {})",
                    stringify!($fn), PROFILE, $storage_dp, stats.max_ulp, $max_ulp as u128, stats.worst_label);
            }
        };
    }

    // Q16.16 storage tier: ~4 fractional decimal digits.
    // Compute headroom = 9 - storage_dp digits.
    // sin/cos/atan: bounded ∈ [-π, π], use storage dp=4
    // ln/sqrt: storage dp=3-4
    storage_ulp_test!(validate_sin,  decimal_sin,  DECIMAL_SIN_REFS,  4, 0);
    storage_ulp_test!(validate_cos,  decimal_cos,  DECIMAL_COS_REFS,  4, 0);
    storage_ulp_test!(validate_atan, decimal_atan, DECIMAL_ATAN_REFS, 4, 0);
    storage_ulp_test!(validate_ln,   decimal_ln,   DECIMAL_LN_REFS,   4, 0);
    storage_ulp_test!(validate_sqrt, decimal_sqrt, DECIMAL_SQRT_REFS, 3, 0);

    /// exp is range-limited on Q16.16: the ln(2) reduction for |x|>10 amplifies
    /// Taylor error by 2^29, exceeding the 9-dp compute precision budget. Users
    /// should restrict exp to |x| ≤ 10 on realtime (result ≤ 22026, ~5 sig digits).
    #[test]
    fn validate_exp() {
        let mut stats = UlpStats::new("decimal_exp");
        // 10^9 = 10e9 compute storage per unit. |input| ≤ 10 → raw ≤ 10e9.
        let max_input_raw: i64 = 10_000_000_000;
        for &(input, expected, label) in DECIMAL_EXP_REFS.iter() {
            if input.abs() > max_input_raw { continue; }
            match decimal_exp(input) {
                Ok(actual) => {
                    let actual_s = downscale_to_dp(actual, 2);
                    let expected_s = downscale_to_dp(expected, 2);
                    stats.record(ulp_i64(actual_s, expected_s), label);
                }
                Err(_) => stats.record_error(label),
            }
        }
        stats.report(PROFILE, 2);
        assert!(stats.max_ulp <= 0,
            "decimal_exp Q16.16 (storage dp=2, |x|≤10) max ULP {} > 0 (worst: {})",
            stats.max_ulp, stats.worst_label);
    }

    #[test]
    fn validate_atan2() {
        let mut stats = UlpStats::new("atan2");
        for &(y, x, expected, label) in DECIMAL_ATAN2_REFS.iter() {
            match decimal_atan2(y, x) {
                Ok(actual) => {
                    let actual_s = downscale_to_dp(actual, 4);
                    let expected_s = downscale_to_dp(expected, 4);
                    stats.record(ulp_i64(actual_s, expected_s), label);
                }
                Err(_) => stats.record_error(label),
            }
        }
        stats.report(PROFILE, 4);
        assert!(stats.max_ulp <= 0,
            "atan2 {} (storage dp=4) max ULP {} > 0 (worst: {})",
            PROFILE, stats.max_ulp, stats.worst_label);
    }
}

// ════════════════════════════════════════════════════════════════════
// Q32.32 Profile — compact (compute_dp = 19, i128)
// ════════════════════════════════════════════════════════════════════

#[cfg(table_format = "q32_32")]
mod q32_32 {
    use super::*;
    use g_math::fixed_point::domains::decimal_fixed::transcendental::{
        decimal_exp, decimal_ln, decimal_sqrt, decimal_sin, decimal_cos, decimal_atan,
        decimal_atan2,
    };

    include!("data/decimal_refs_q32_32.rs");
    const COMPUTE_DP: u32 = 19;
    const PROFILE: &str = "Q32.32";

    fn ulp_i128(actual: i128, expected: i128) -> u128 {
        (actual - expected).unsigned_abs()
    }

    /// Downscale i128 value at compute_dp=19 to target_dp with round-half-up.
    fn downscale_to_dp(v: i128, target_dp: u32) -> i128 {
        if target_dp >= 19 { return v; }
        let diff = 19 - target_dp;
        let mut divisor: i128 = 1;
        for _ in 0..diff { divisor *= 10; }
        let half = divisor / 2;
        let rounded = if v < 0 { v - half } else { v + half };
        rounded / divisor
    }

    macro_rules! storage_ulp_test {
        ($name:ident, $fn:ident, $refs:ident, $storage_dp:expr, $max_ulp:expr) => {
            #[test]
            fn $name() {
                let mut stats = UlpStats::new(stringify!($fn));
                if let Some(&(input, _, _)) = $refs.first() {
                    let _ = $fn(input);
                }
                const PASSES: usize = 8;
                let start = std::time::Instant::now();
                for _ in 0..PASSES {
                    for &(input, expected, label) in $refs.iter() {
                        match $fn(input) {
                            Ok(actual) => {
                                let actual_s = downscale_to_dp(actual, $storage_dp);
                                let expected_s = downscale_to_dp(expected, $storage_dp);
                                stats.record(ulp_i128(actual_s, expected_s), label);
                            }
                            Err(_) => stats.record_error(label),
                        }
                    }
                }
                let elapsed = start.elapsed();
                stats.report_throughput(PROFILE, $storage_dp, elapsed);
                assert!(stats.max_ulp <= $max_ulp,
                    "{} {} (storage dp={}) max ULP {} > {} (worst: {})",
                    stringify!($fn), PROFILE, $storage_dp, stats.max_ulp, $max_ulp as u128, stats.worst_label);
            }
        };
    }

    // Q32.32 storage tier: ~9 fractional decimal digits.
    // Compute_dp = 19, allowing ~10 dp of headroom for storage_dp = 9.
    storage_ulp_test!(validate_sin,  decimal_sin,  DECIMAL_SIN_REFS,  14, 0);
    storage_ulp_test!(validate_cos,  decimal_cos,  DECIMAL_COS_REFS,  14, 0);
    storage_ulp_test!(validate_atan, decimal_atan, DECIMAL_ATAN_REFS, 14, 0);
    storage_ulp_test!(validate_ln,   decimal_ln,   DECIMAL_LN_REFS,   13, 0);
    storage_ulp_test!(validate_sqrt, decimal_sqrt, DECIMAL_SQRT_REFS, 12, 0);
    // exp on Q32.32: full [-20, 20] range, dp=7 gives enough headroom for 2^29 shift
    storage_ulp_test!(validate_exp,  decimal_exp,  DECIMAL_EXP_REFS,  7,  0);

    #[test]
    fn validate_atan2() {
        let mut stats = UlpStats::new("atan2");
        for &(y, x, expected, label) in DECIMAL_ATAN2_REFS.iter() {
            match decimal_atan2(y, x) {
                Ok(actual) => {
                    let actual_s = downscale_to_dp(actual, 14);
                    let expected_s = downscale_to_dp(expected, 14);
                    stats.record(ulp_i128(actual_s, expected_s), label);
                }
                Err(_) => stats.record_error(label),
            }
        }
        stats.report(PROFILE, 14);
        assert!(stats.max_ulp <= 0,
            "atan2 {} (storage dp=14) max ULP {} > 0 (worst: {})",
            PROFILE, stats.max_ulp, stats.worst_label);
    }
}

// ════════════════════════════════════════════════════════════════════
// Q64.64 Profile — embedded (compute_dp = 38, I256)
// ════════════════════════════════════════════════════════════════════

#[cfg(table_format = "q64_64")]
mod q64_64 {
    use super::*;
    use g_math::fixed_point::domains::decimal_fixed::transcendental::{
        decimal_exp, decimal_ln, decimal_sqrt, decimal_sin, decimal_cos, decimal_atan,
        decimal_atan2,
    };
    use g_math::fixed_point::i256::I256;

    include!("data/decimal_refs_q64_64.rs");
    const COMPUTE_DP: u32 = 38;
    const PROFILE: &str = "Q64.64";

    fn i256_from_words(w: [u64; 4]) -> I256 {
        I256::from_words(w)
    }

    fn ulp_i256(actual: I256, expected: I256) -> u128 {
        let diff = actual - expected;
        let is_neg = (diff.words[3] >> 63) == 1;
        let abs_diff = if is_neg { -diff } else { diff };
        if abs_diff.words[2] != 0 || abs_diff.words[3] != 0 {
            return u128::MAX;
        }
        abs_diff.words[0] as u128 | ((abs_diff.words[1] as u128) << 64)
    }

    macro_rules! unary_test {
        ($name:ident, $fn:ident, $refs:ident, $max_ulp:expr) => {
            #[test]
            fn $name() {
                let mut stats = UlpStats::new(stringify!($fn));
                for &(input_w, expected_w, label) in $refs.iter() {
                    let input = i256_from_words(input_w);
                    let expected = i256_from_words(expected_w);
                    match $fn(input) {
                        Ok(actual) => stats.record(ulp_i256(actual, expected), label),
                        Err(_) => stats.record_error(label),
                    }
                }
                stats.report(PROFILE, COMPUTE_DP);
                assert!(stats.max_ulp <= $max_ulp,
                    "{} {} max ULP {} > {} (worst: {})",
                    stringify!($fn), PROFILE, stats.max_ulp, $max_ulp as u128, stats.worst_label);
            }
        };
    }

    /// Compute "relative ULP at compute dp" — absolute ULP normalized by result magnitude.
    ///
    /// For an expected value `e` and absolute error `err`:
    ///   `relative_ulp = err × scale / max(scale, |e|)`
    /// where `scale = 10^DECIMAL_COMPUTE_DP`.
    ///
    /// This gives "ULP-of-1.0 at compute dp" — magnitude-independent precision measure.
    /// For values with `|e| ≥ 1`, it's the relative error scaled to `1.0` units.
    fn relative_ulp_i256(actual: I256, expected: I256) -> u128 {
        let abs_diff_u128 = ulp_i256(actual, expected);
        let abs_expected = if expected.is_negative() { I256::zero() - expected } else { expected };

        use g_math::fixed_point::domains::decimal_fixed::transcendental::decimal_compute::decimal_compute_scale;
        let scale = decimal_compute_scale();

        // If |expected| < scale, use absolute ULP unchanged (relative-to-1.0 baseline)
        if abs_expected < scale {
            return abs_diff_u128;
        }

        // relative = abs_diff × scale / |expected|, computed in I512 to avoid overflow
        use g_math::fixed_point::i512::I512;
        // abs_diff_u128 may exceed i128::MAX. Convert via two halves.
        let diff_low = abs_diff_u128 as u64;
        let diff_high = (abs_diff_u128 >> 64) as u64;
        let diff_i256 = I256::from_words([diff_low, diff_high, 0, 0]);
        let diff_wide = I512::from_i256(diff_i256);
        let scale_wide = I512::from_i256(scale);
        let exp_wide = I512::from_i256(abs_expected);

        let prod = diff_wide * scale_wide;
        let result = prod / exp_wide;

        // Extract result as u128 (for relative ULP up to ~10^18, fits easily)
        let r_i256 = result.as_i256();
        if r_i256.words[2] != 0 || r_i256.words[3] != 0 {
            return u128::MAX;
        }
        r_i256.words[0] as u128 | ((r_i256.words[1] as u128) << 64)
    }

    macro_rules! relative_unary_test {
        ($name:ident, $fn:ident, $refs:ident, $max_relative_ulp:expr) => {
            #[test]
            fn $name() {
                let mut stats = UlpStats::new(stringify!($fn));
                for &(input_w, expected_w, label) in $refs.iter() {
                    let input = i256_from_words(input_w);
                    let expected = i256_from_words(expected_w);
                    match $fn(input) {
                        Ok(actual) => stats.record(relative_ulp_i256(actual, expected), label),
                        Err(_) => stats.record_error(label),
                    }
                }
                stats.report(PROFILE, COMPUTE_DP);
                assert!(stats.max_ulp <= $max_relative_ulp,
                    "{} {} max RELATIVE ULP {} > {} (worst: {})",
                    stringify!($fn), PROFILE, stats.max_ulp, $max_relative_ulp as u128, stats.worst_label);
            }
        };
    }

    /// Downscale an I256 value at compute dp=38 to dp=`target_dp` with round-half-up.
    /// Returns the downscaled raw integer.
    fn downscale_to_dp(v: I256, target_dp: u32) -> I256 {
        if target_dp >= 38 {
            return v;
        }
        let diff = 38 - target_dp;
        // Build 10^diff
        let mut divisor = I256::from_i128(1);
        let ten = I256::from_i128(10);
        for _ in 0..diff {
            divisor = divisor * ten;
        }
        let half = I256 { words: [
            divisor.words[0] >> 1 | (divisor.words[1] << 63),
            divisor.words[1] >> 1 | (divisor.words[2] << 63),
            divisor.words[2] >> 1 | (divisor.words[3] << 63),
            divisor.words[3] >> 1,
        ]};
        let rounded = if v.is_negative() { v - half } else { v + half };
        rounded / divisor
    }

    /// Storage-tier ULP test: downscale BOTH actual and expected from compute dp=38
    /// to a target storage dp, then compare. This is the **decimal equivalent of
    /// binary exactness at storage tier** — the algorithmic compute-tier error gets
    /// absorbed into the rounding when stepping down to storage precision.
    macro_rules! storage_ulp_test {
        ($name:ident, $fn:ident, $refs:ident, $storage_dp:expr, $max_ulp:expr) => {
            #[test]
            fn $name() {
                let mut stats = UlpStats::new(stringify!($fn));
                if let Some(&(input_w, _, _)) = $refs.first() {
                    let _ = $fn(i256_from_words(input_w));
                }
                const PASSES: usize = 8;
                let start = std::time::Instant::now();
                for _ in 0..PASSES {
                    for &(input_w, expected_w, label) in $refs.iter() {
                        let input = i256_from_words(input_w);
                        let expected_compute = i256_from_words(expected_w);
                        match $fn(input) {
                            Ok(actual_compute) => {
                                let actual_storage = downscale_to_dp(actual_compute, $storage_dp);
                                let expected_storage = downscale_to_dp(expected_compute, $storage_dp);
                                stats.record(ulp_i256(actual_storage, expected_storage), label);
                            }
                            Err(_) => stats.record_error(label),
                        }
                    }
                }
                let elapsed = start.elapsed();
                stats.report_throughput(PROFILE, $storage_dp, elapsed);
                assert!(stats.max_ulp <= $max_ulp,
                    "{} {} (storage dp={}) max ULP {} > {} (worst: {})",
                    stringify!($fn), PROFILE, $storage_dp, stats.max_ulp, $max_ulp as u128, stats.worst_label);
            }
        };
    }

    // ==================================================================
    // STORAGE-TIER ULP VALIDATION — the exact-at-storage-tier target matching binary
    // ==================================================================
    //
    // Each function is tested at the maximum dp where its result range fits
    // in i128 storage. This mirrors what users actually get when materializing
    // a Decimal from a transcendental computation.
    //
    // Compute tier (dp=38) provides ~19 dp of headroom over storage, absorbing
    // all algorithmic error during downscaling. Result: exact at storage tier,
    // matching the binary transcendental behavior.
    //
    // sin/cos/atan/atan2: result ∈ [-π, π], 1 integer digit → max storage dp ≤ 37
    // exp: result up to ~5e8 for our range, ~9 integer digits → max storage dp ≤ 29
    // ln: result up to ~9 for our range, 1 integer digit → max storage dp ≤ 37
    // sqrt: result up to ~100, 3 integer digits → max storage dp ≤ 35
    //
    // Storage dp choice: must give enough headroom for the worst-case compute-tier
    // error to fall safely inside the storage rounding boundary on BOTH sides.
    // Rule of thumb: 10^(38 - storage_dp) > 100 × max_compute_ulps.

    storage_ulp_test!(validate_sin_storage,   decimal_sin,   DECIMAL_SIN_REFS,   33, 0);
    storage_ulp_test!(validate_cos_storage,   decimal_cos,   DECIMAL_COS_REFS,   33, 0);
    storage_ulp_test!(validate_atan_storage,  decimal_atan,  DECIMAL_ATAN_REFS,  33, 0);
    storage_ulp_test!(validate_exp_storage,   decimal_exp,   DECIMAL_EXP_REFS,   25, 0);
    storage_ulp_test!(validate_ln_storage,    decimal_ln,    DECIMAL_LN_REFS,    32, 0);
    storage_ulp_test!(validate_sqrt_storage,  decimal_sqrt,  DECIMAL_SQRT_REFS,  30, 0);

    #[test]
    fn validate_atan2_storage() {
        let mut stats = UlpStats::new("atan2");
        for &(y_w, x_w, expected_w, label) in DECIMAL_ATAN2_REFS.iter() {
            let y = i256_from_words(y_w);
            let x = i256_from_words(x_w);
            let expected_compute = i256_from_words(expected_w);
            match decimal_atan2(y, x) {
                Ok(actual_compute) => {
                    let actual_storage = downscale_to_dp(actual_compute, 33);
                    let expected_storage = downscale_to_dp(expected_compute, 33);
                    stats.record(ulp_i256(actual_storage, expected_storage), label);
                }
                Err(_) => stats.record_error(label),
            }
        }
        stats.report(PROFILE, 33);
        assert!(stats.max_ulp <= 0,
            "atan2 {} (storage dp=33) max ULP {} > 0 (worst: {})",
            PROFILE, stats.max_ulp, stats.worst_label);
    }

    // Thresholds at compute dp = 38.
    // For functions where the result magnitude doesn't vary much (sin/cos/atan,
    // bounded in [-π, π]), absolute ULP is a good metric.
    //
    // For exp/sqrt/ln where the result spans many orders of magnitude, we use
    // RELATIVE ULP measurement: scale absolute ULP by max(1, |expected|/scale)
    // so that errors in large-magnitude results are normalized.
    //
    // Pure absolute ULP (suitable for bounded-output functions):
    unary_test!(validate_sin,  decimal_sin,  DECIMAL_SIN_REFS,  500);
    unary_test!(validate_cos,  decimal_cos,  DECIMAL_COS_REFS,  500);
    unary_test!(validate_atan, decimal_atan, DECIMAL_ATAN_REFS, 500);

    // Functions with magnitude variation — use relative ULP measurement.
    // Thresholds reflect relative precision at compute dp (10^-38 baseline).
    // 500 relative ULP = ~10^-35 relative error = 35 correct decimal digits.
    relative_unary_test!(validate_exp,  decimal_exp,  DECIMAL_EXP_REFS,  500);
    relative_unary_test!(validate_ln,   decimal_ln,   DECIMAL_LN_REFS,   10_000);
    // sqrt: small inputs (1e-10) have 1e-35 absolute error, well below storage dp
    relative_unary_test!(validate_sqrt, decimal_sqrt, DECIMAL_SQRT_REFS, 2_000);

    #[test]
    fn validate_atan2() {
        let mut stats = UlpStats::new("atan2");
        for &(y_w, x_w, expected_w, label) in DECIMAL_ATAN2_REFS.iter() {
            let y = i256_from_words(y_w);
            let x = i256_from_words(x_w);
            let expected = i256_from_words(expected_w);
            match decimal_atan2(y, x) {
                Ok(actual) => stats.record(ulp_i256(actual, expected), label),
                Err(_) => stats.record_error(label),
            }
        }
        stats.report(PROFILE, COMPUTE_DP);
        assert!(stats.max_ulp <= 500,
            "atan2 {} max ULP {} > 500 (worst: {})",
            PROFILE, stats.max_ulp, stats.worst_label);
    }
}

// ════════════════════════════════════════════════════════════════════
// Q128.128 Profile — balanced (compute_dp = 77, I512)
// ════════════════════════════════════════════════════════════════════

#[cfg(table_format = "q128_128")]
mod q128_128 {
    use super::*;
    use g_math::fixed_point::domains::decimal_fixed::transcendental::{
        decimal_exp, decimal_ln, decimal_sqrt, decimal_sin, decimal_cos, decimal_atan,
        decimal_atan2,
    };
    use g_math::fixed_point::i512::I512;

    include!("data/decimal_refs_q128_128.rs");
    const COMPUTE_DP: u32 = 77;
    const PROFILE: &str = "Q128.128";

    fn i512_from_words(w: [u64; 8]) -> I512 {
        I512::from_words(w)
    }

    fn ulp_i512(actual: I512, expected: I512) -> u128 {
        let diff = actual - expected;
        let is_neg = diff.is_negative();
        let abs_diff = if is_neg { I512::zero() - diff } else { diff };
        // ULP > 2^128 → return MAX (catastrophic error)
        for i in 2..8 {
            if abs_diff.words[i] != 0 {
                return u128::MAX;
            }
        }
        abs_diff.words[0] as u128 | ((abs_diff.words[1] as u128) << 64)
    }

    /// Downscale I512 value at compute_dp=77 to target_dp with round-half-up.
    fn downscale_to_dp(v: I512, target_dp: u32) -> I512 {
        if target_dp >= 77 { return v; }
        let diff = 77 - target_dp;
        let mut divisor = I512::from_i128(1);
        let ten = I512::from_i128(10);
        for _ in 0..diff { divisor = divisor * ten; }
        let half = divisor >> 1usize;
        let rounded = if v.is_negative() { v - half } else { v + half };
        rounded / divisor
    }

    macro_rules! storage_ulp_test {
        ($name:ident, $fn:ident, $refs:ident, $storage_dp:expr, $max_ulp:expr) => {
            #[test]
            fn $name() {
                let mut stats = UlpStats::new(stringify!($fn));
                if let Some(&(input_w, _, _)) = $refs.first() {
                    let _ = $fn(i512_from_words(input_w));
                }
                const PASSES: usize = 4;
                let start = std::time::Instant::now();
                for _ in 0..PASSES {
                    for &(input_w, expected_w, label) in $refs.iter() {
                        let input = i512_from_words(input_w);
                        let expected = i512_from_words(expected_w);
                        match $fn(input) {
                            Ok(actual) => {
                                let actual_s = downscale_to_dp(actual, $storage_dp);
                                let expected_s = downscale_to_dp(expected, $storage_dp);
                                stats.record(ulp_i512(actual_s, expected_s), label);
                            }
                            Err(_) => stats.record_error(label),
                        }
                    }
                }
                let elapsed = start.elapsed();
                stats.report_throughput(PROFILE, $storage_dp, elapsed);
                assert!(stats.max_ulp <= $max_ulp,
                    "{} {} (storage dp={}) max ULP {} > {} (worst: {})",
                    stringify!($fn), PROFILE, $storage_dp, stats.max_ulp, $max_ulp as u128, stats.worst_label);
            }
        };
    }

    // Q128.128 storage tier: ~38 fractional decimal digits.
    // Compute_dp = 77, allowing huge headroom. Target storage dp ≈ 65-70.
    storage_ulp_test!(validate_sin,  decimal_sin,  DECIMAL_SIN_REFS,  68, 0);
    storage_ulp_test!(validate_cos,  decimal_cos,  DECIMAL_COS_REFS,  68, 0);
    storage_ulp_test!(validate_atan, decimal_atan, DECIMAL_ATAN_REFS, 68, 0);
    storage_ulp_test!(validate_ln,   decimal_ln,   DECIMAL_LN_REFS,   65, 0);
    storage_ulp_test!(validate_sqrt, decimal_sqrt, DECIMAL_SQRT_REFS, 65, 0);
    storage_ulp_test!(validate_exp,  decimal_exp,  DECIMAL_EXP_REFS,  60, 0);

    #[test]
    fn validate_atan2() {
        let mut stats = UlpStats::new("atan2");
        for &(y_w, x_w, expected_w, label) in DECIMAL_ATAN2_REFS.iter() {
            let y = i512_from_words(y_w);
            let x = i512_from_words(x_w);
            let expected = i512_from_words(expected_w);
            match decimal_atan2(y, x) {
                Ok(actual) => {
                    let actual_s = downscale_to_dp(actual, 68);
                    let expected_s = downscale_to_dp(expected, 68);
                    stats.record(ulp_i512(actual_s, expected_s), label);
                }
                Err(_) => stats.record_error(label),
            }
        }
        stats.report(PROFILE, 68);
        assert!(stats.max_ulp <= 0,
            "atan2 {} (storage dp=68) max ULP {} > 0 (worst: {})",
            PROFILE, stats.max_ulp, stats.worst_label);
    }
}

// ════════════════════════════════════════════════════════════════════
// Q256.256 Profile — scientific (compute_dp = 154, I1024)
// ════════════════════════════════════════════════════════════════════

#[cfg(table_format = "q256_256")]
mod q256_256 {
    use super::*;
    use g_math::fixed_point::domains::decimal_fixed::transcendental::{
        decimal_exp, decimal_ln, decimal_sqrt, decimal_sin, decimal_cos, decimal_atan,
        decimal_atan2,
    };
    use g_math::fixed_point::I1024;

    include!("data/decimal_refs_q256_256.rs");
    const COMPUTE_DP: u32 = 154;
    const PROFILE: &str = "Q256.256";

    fn i1024_from_words(w: [u64; 16]) -> I1024 {
        I1024::from_words(w)
    }

    fn ulp_i1024(actual: I1024, expected: I1024) -> u128 {
        let diff = actual - expected;
        let is_neg = (diff.words[15] as i64) < 0;
        let abs_diff = if is_neg { I1024::zero() - diff } else { diff };
        for i in 2..16 {
            if abs_diff.words[i] != 0 {
                return u128::MAX;
            }
        }
        abs_diff.words[0] as u128 | ((abs_diff.words[1] as u128) << 64)
    }

    /// Downscale I1024 value at compute_dp=154 to target_dp with round-half-up.
    fn downscale_to_dp(v: I1024, target_dp: u32) -> I1024 {
        if target_dp >= 154 { return v; }
        let diff = 154 - target_dp;
        let mut divisor = I1024::from_i128(1);
        let ten = I1024::from_i128(10);
        for _ in 0..diff { divisor = divisor * ten; }
        let half = divisor >> 1usize;
        let v_neg = (v.words[15] as i64) < 0;
        let rounded = if v_neg { v - half } else { v + half };
        rounded / divisor
    }

    macro_rules! storage_ulp_test {
        ($name:ident, $fn:ident, $refs:ident, $storage_dp:expr, $max_ulp:expr) => {
            #[test]
            fn $name() {
                let mut stats = UlpStats::new(stringify!($fn));
                if let Some(&(input_w, _, _)) = $refs.first() {
                    let _ = $fn(i1024_from_words(input_w));
                }
                // Scientific is slow — use fewer passes
                const PASSES: usize = 2;
                let start = std::time::Instant::now();
                for _ in 0..PASSES {
                    for &(input_w, expected_w, label) in $refs.iter() {
                        let input = i1024_from_words(input_w);
                        let expected = i1024_from_words(expected_w);
                        match $fn(input) {
                            Ok(actual) => {
                                let actual_s = downscale_to_dp(actual, $storage_dp);
                                let expected_s = downscale_to_dp(expected, $storage_dp);
                                stats.record(ulp_i1024(actual_s, expected_s), label);
                            }
                            Err(_) => stats.record_error(label),
                        }
                    }
                }
                let elapsed = start.elapsed();
                stats.report_throughput(PROFILE, $storage_dp, elapsed);
                assert!(stats.max_ulp <= $max_ulp,
                    "{} {} (storage dp={}) max ULP {} > {} (worst: {})",
                    stringify!($fn), PROFILE, $storage_dp, stats.max_ulp, $max_ulp as u128, stats.worst_label);
            }
        };
    }

    // Q256.256 storage tier: ~77 fractional decimal digits.
    // Compute_dp = 154, allowing huge headroom. Target storage dp ≈ 130-145.
    storage_ulp_test!(validate_sin,  decimal_sin,  DECIMAL_SIN_REFS,  140, 0);
    storage_ulp_test!(validate_cos,  decimal_cos,  DECIMAL_COS_REFS,  140, 0);
    storage_ulp_test!(validate_atan, decimal_atan, DECIMAL_ATAN_REFS, 140, 0);
    storage_ulp_test!(validate_ln,   decimal_ln,   DECIMAL_LN_REFS,   135, 0);
    storage_ulp_test!(validate_sqrt, decimal_sqrt, DECIMAL_SQRT_REFS, 135, 0);
    storage_ulp_test!(validate_exp,  decimal_exp,  DECIMAL_EXP_REFS,  130, 0);

    #[test]
    fn validate_atan2() {
        let mut stats = UlpStats::new("atan2");
        for &(y_w, x_w, expected_w, label) in DECIMAL_ATAN2_REFS.iter() {
            let y = i1024_from_words(y_w);
            let x = i1024_from_words(x_w);
            let expected = i1024_from_words(expected_w);
            match decimal_atan2(y, x) {
                Ok(actual) => {
                    let actual_s = downscale_to_dp(actual, 140);
                    let expected_s = downscale_to_dp(expected, 140);
                    stats.record(ulp_i1024(actual_s, expected_s), label);
                }
                Err(_) => stats.record_error(label),
            }
        }
        stats.report(PROFILE, 140);
        assert!(stats.max_ulp <= 0,
            "atan2 {} (storage dp=140) max ULP {} > 0 (worst: {})",
            PROFILE, stats.max_ulp, stats.worst_label);
    }
}
