//! Convergence and correctness gate for the iterative decompositions:
//! `svd_decompose` (Golub-Kahan), `eigen_symmetric` (Jacobi) and
//! `schur_decompose` (Francis).
//!
//! Every case is checked against the definition of its decomposition
//! (reconstruction, orthogonality, and for Schur the exact quasi-triangular
//! structure) and its spectrum against independent references
//! (`tests/data/decomposition_refs.rs`, generated by
//! `scripts/generate_decomposition_refs.py`: mpmath at 120 digits,
//! cross-checked against exact characteristic-polynomial roots). The cases are
//! the inputs that exposed silent failures in 0.6.1: exactly rank-deficient
//! matrices, bidiagonal inputs with an interior zero diagonal, 2×2 blocks with
//! real eigenvalues and a bulge chase one step short in Schur, permutation
//! matrices, and entries whose squares leave the storage range. Every
//! decomposition must succeed on every case; the bounds are measured per
//! profile, not derived.

use g_math::fixed_point::imperative::decompose::{eigen_symmetric, schur_decompose, svd_decompose};
use g_math::fixed_point::{FixedMatrix, FixedPoint, FixedVector, OverflowDetected};

#[allow(dead_code)]
mod data {
    include!("data/decomposition_refs.rs");
}
use data::Case;

// ============================================================================
// Units, references, measurements
// ============================================================================

/// |x| in ulps (saturating at `i128::MAX` on the wide profiles).
fn ulps(x: FixedPoint) -> i128 {
    let raw = x.abs().raw();
    #[cfg(any(table_format = "q16_16", table_format = "q32_32", table_format = "q64_64"))]
    {
        raw as i128
    }
    #[cfg(any(table_format = "q128_128", table_format = "q256_256"))]
    {
        if raw.fits_in_i128() { raw.as_i128() } else { i128::MAX }
    }
}

/// A decimal reference to the nearest storage value, within one ulp: Horner
/// over four-digit fraction groups from the last, one rounded division per
/// group, so each earlier rounding is divided away by the next group.
fn reference(s: &str) -> FixedPoint {
    let (negative, body) = match s.strip_prefix('-') {
        Some(rest) => (true, rest),
        None => (false, s),
    };
    let (int_part, frac_part) = body.split_once('.').unwrap_or((body, ""));
    let group_scale = FixedPoint::from_int(10_000);
    let mut acc = FixedPoint::ZERO;
    for group in frac_part.as_bytes().chunks(4).rev() {
        let mut value = 0i32;
        for k in 0..4 {
            value = value * 10 + group.get(k).map_or(0, |d| (d - b'0') as i32);
        }
        acc = (FixedPoint::from_int(value) + acc) / group_scale;
    }
    let magnitude = FixedPoint::from_int(int_part.parse::<i32>().expect("integer part")) + acc;
    if negative { -magnitude } else { magnitude }
}

fn build(case: &Case) -> FixedMatrix {
    let divisor = FixedPoint::from_int(1 << case.shift);
    FixedMatrix::from_fn(case.rows, case.cols, |i, j| {
        FixedPoint::from_int(case.entries[i * case.cols + j]) / divisor
    })
}

fn max_abs_diff(a: &FixedMatrix, b: &FixedMatrix) -> FixedPoint {
    let mut worst = FixedPoint::ZERO;
    for i in 0..a.rows() {
        for j in 0..a.cols() {
            worst = worst.max((a.get(i, j) - b.get(i, j)).abs());
        }
    }
    worst
}

fn diagonal(rows: usize, cols: usize, values: &FixedVector) -> FixedMatrix {
    FixedMatrix::from_fn(rows, cols, |r, c| if r == c { values[r] } else { FixedPoint::ZERO })
}

/// A power of two at half the storage maximum.
fn half_max() -> FixedPoint {
    let mut x = FixedPoint::one();
    loop {
        let doubled = x + x;
        if doubled <= x {
            return x;
        }
        x = doubled;
    }
}

/// Largest spectrum, reconstruction and orthogonality errors of one case, in ulps.
#[derive(Debug)]
struct Measured {
    case: &'static str,
    spectrum: i128,
    reconstruction: i128,
    orthogonality: i128,
}

fn measure_svd(case: &Case, refs: &[&str]) -> Measured {
    let a = build(case);
    let svd = svd_decompose(&a).unwrap_or_else(|e| panic!("{}: svd_decompose returned {e:?}", case.name));
    assert_eq!(svd.sigma.len(), refs.len(), "{}: singular value count", case.name);
    let spectrum = (0..refs.len()).map(|i| ulps(svd.sigma[i] - reference(refs[i]))).max().unwrap_or(0);
    let rebuilt = &(&svd.u * &diagonal(a.rows(), a.cols(), &svd.sigma)) * &svd.vt;
    let orth_u = max_abs_diff(&(&svd.u.transpose() * &svd.u), &FixedMatrix::identity(svd.u.rows()));
    let orth_v = max_abs_diff(&(&svd.vt * &svd.vt.transpose()), &FixedMatrix::identity(svd.vt.rows()));
    Measured {
        case: case.name,
        spectrum,
        reconstruction: ulps(max_abs_diff(&rebuilt, &a)),
        orthogonality: ulps(orth_u.max(orth_v)),
    }
}

fn measure_eigen(case: &Case, refs: &[&str]) -> Measured {
    let a = build(case);
    let n = a.rows();
    let eig = eigen_symmetric(&a).unwrap_or_else(|e| panic!("{}: eigen_symmetric returned {e:?}", case.name));
    let mut values: Vec<FixedPoint> = (0..n).map(|i| eig.values[i]).collect();
    values.sort();
    let spectrum = (0..n).map(|i| ulps(values[i] - reference(refs[i]))).max().unwrap_or(0);
    let rebuilt = &(&eig.vectors * &diagonal(n, n, &eig.values)) * &eig.vectors.transpose();
    let orth = max_abs_diff(&(&eig.vectors.transpose() * &eig.vectors), &FixedMatrix::identity(n));
    Measured {
        case: case.name,
        spectrum,
        reconstruction: ulps(max_abs_diff(&rebuilt, &a)),
        orthogonality: ulps(orth),
    }
}

/// Every entry below the subdiagonal is exactly zero, no two consecutive
/// subdiagonal entries are nonzero, and every 2×2 block has a complex pair.
fn assert_real_schur_form(name: &str, t: &FixedMatrix) {
    let n = t.rows();
    for i in 0..n {
        for j in 0..n {
            if i > j + 1 {
                assert!(t.get(i, j).is_zero(), "{name}: T[{i},{j}] = {} below the subdiagonal", t.get(i, j));
            }
        }
    }
    for i in 1..n.saturating_sub(1) {
        assert!(
            t.get(i, i - 1).is_zero() || t.get(i + 1, i).is_zero(),
            "{name}: consecutive nonzero subdiagonal entries at rows {i}, {}",
            i + 1
        );
    }
}

/// Eigenvalues read from a real Schur form, sorted by (re, im).
fn schur_spectrum(name: &str, t: &FixedMatrix) -> Vec<(FixedPoint, FixedPoint)> {
    let n = t.rows();
    let half = FixedPoint::one() / FixedPoint::from_int(2);
    let mut out = Vec::with_capacity(n);
    let mut i = 0;
    while i < n {
        if i + 1 < n && !t.get(i + 1, i).is_zero() {
            let (a, b) = (t.get(i, i), t.get(i, i + 1));
            let (c, d) = (t.get(i + 1, i), t.get(i + 1, i + 1));
            let re = (a + d) * half;
            let p = (a - d) * half;
            let disc = p * p + b * c;
            assert!(disc.is_negative(), "{name}: 2x2 block at {i} has real eigenvalues (discriminant {disc})");
            let im = (-disc).sqrt();
            out.push((re, -im));
            out.push((re, im));
            i += 2;
        } else {
            out.push((t.get(i, i), FixedPoint::ZERO));
            i += 1;
        }
    }
    out.sort();
    out
}

fn measure_schur(case: &Case, refs: &[(&str, &str)]) -> Measured {
    let a = build(case);
    let n = a.rows();
    let schur = schur_decompose(&a).unwrap_or_else(|e| panic!("{}: schur_decompose returned {e:?}", case.name));
    assert_real_schur_form(case.name, &schur.t);
    let values = schur_spectrum(case.name, &schur.t);
    let spectrum = values
        .iter()
        .zip(refs)
        .map(|((re, im), (ref_re, ref_im))| ulps(*re - reference(ref_re)).max(ulps(*im - reference(ref_im))))
        .max()
        .unwrap_or(0);
    let rebuilt = &(&schur.q * &schur.t) * &schur.q.transpose();
    let orth = max_abs_diff(&(&schur.q.transpose() * &schur.q), &FixedMatrix::identity(n));
    Measured {
        case: case.name,
        spectrum,
        reconstruction: ulps(max_abs_diff(&rebuilt, &a)),
        orthogonality: ulps(orth),
    }
}

// ============================================================================
// Measured bounds (ulps), per profile
// ============================================================================

struct Bounds {
    spectrum: i128,
    reconstruction: i128,
    orthogonality: i128,
}

struct ProfileBounds {
    svd: Bounds,
    eigen: Bounds,
    schur: Bounds,
    /// Spectrum error on the large-entry pattern matrices.
    large_entries: i128,
    /// Worst |y - W x| / |W x| of the consumer's matvec through the SVD, in
    /// units of 1/1000.
    consumer_per_mille: Option<i32>,
}

// Bounds are the measured maxima over the cases, doubled, and at least 4 ulp.
// The decompositions are deterministic, so the doubling is headroom for
// deliberate algorithm changes, not for noise. Reconstruction and Schur
// eigenvalue errors follow the relative deflation bound (2^-(2F/3) of the
// neighbouring magnitudes) and grow with the profile; spectrum errors of the
// symmetric problems stay at a few ulp. realtime covers GMATH_FRAC_BITS 16
// and 10 (the configuration the SVD failure was reported on).

// Measured, Q16.16 / Q22.10: SVD 18/14 13 ulp, 14035/4261, 7/9; EIGEN 212/5,
// 41673/3046, 5/5; SCHUR 888/288, 169/108, 5/17; large entries 1/777;
// consumer 0.318/21.650 per mille.
#[cfg(table_format = "q16_16")]
const BOUNDS: ProfileBounds = ProfileBounds {
    svd: Bounds { spectrum: 36, reconstruction: 28_070, orthogonality: 18 },
    eigen: Bounds { spectrum: 424, reconstruction: 83_346, orthogonality: 10 },
    schur: Bounds { spectrum: 1_776, reconstruction: 338, orthogonality: 34 },
    large_entries: 1_554,
    consumer_per_mille: Some(44),
};

// Measured: SVD 5, 784821, 7; EIGEN 4, 382866, 5; SCHUR 105716, 5689, 6;
// large entries 0; consumer 0.0033 per mille.
#[cfg(table_format = "q32_32")]
const BOUNDS: ProfileBounds = ProfileBounds {
    svd: Bounds { spectrum: 10, reconstruction: 1_569_642, orthogonality: 14 },
    eigen: Bounds { spectrum: 8, reconstruction: 765_732, orthogonality: 10 },
    schur: Bounds { spectrum: 211_432, reconstruction: 11_378, orthogonality: 12 },
    large_entries: 4,
    consumer_per_mille: Some(1),
};

// Measured: SVD 9, 120899440, 17; EIGEN 4, 53730421, 6; SCHUR 19728208,
// 13598728, 6; large entries 0.
#[cfg(table_format = "q64_64")]
const BOUNDS: ProfileBounds = ProfileBounds {
    svd: Bounds { spectrum: 18, reconstruction: 241_798_880, orthogonality: 34 },
    eigen: Bounds { spectrum: 8, reconstruction: 107_460_842, orthogonality: 12 },
    schur: Bounds { spectrum: 39_456_416, reconstruction: 27_197_456, orthogonality: 12 },
    large_entries: 4,
    consumer_per_mille: Some(1),
};

// Measured: SVD 4, 53635673698058, 13; EIGEN 4, 14812482421293, 8; SCHUR
// 2051743236, 2051151661, 6; large entries 1.
#[cfg(table_format = "q128_128")]
const BOUNDS: ProfileBounds = ProfileBounds {
    svd: Bounds { spectrum: 8, reconstruction: 107_271_347_396_116, orthogonality: 26 },
    eigen: Bounds { spectrum: 8, reconstruction: 29_624_964_842_586, orthogonality: 16 },
    schur: Bounds { spectrum: 4_103_486_472, reconstruction: 4_102_303_322, orthogonality: 12 },
    large_entries: 4,
    consumer_per_mille: Some(1),
};

// Measured: SVD 5, 310000759421178177745326185, 9; EIGEN 5,
// 134357540171219206938798178, 7; SCHUR 4066454156856757657,
// 30469357409272137978, 9; large entries 1.
#[cfg(table_format = "q256_256")]
const BOUNDS: ProfileBounds = ProfileBounds {
    svd: Bounds { spectrum: 10, reconstruction: 620_001_518_842_356_355_490_652_370, orthogonality: 18 },
    eigen: Bounds { spectrum: 10, reconstruction: 268_715_080_342_438_413_877_596_356, orthogonality: 14 },
    schur: Bounds {
        spectrum: 8_132_908_313_713_515_314,
        reconstruction: 60_938_714_818_544_275_956,
        orthogonality: 18,
    },
    large_entries: 4,
    consumer_per_mille: Some(1),
};

fn check(kind: &str, m: &Measured, b: &Bounds) {
    println!(
        "{kind:5} {:32} spectrum {:>12} ulp  reconstruction {:>12} ulp  orthogonality {:>8} ulp",
        m.case, m.spectrum, m.reconstruction, m.orthogonality
    );
    assert!(m.spectrum <= b.spectrum, "{kind} {}: spectrum error {} ulp > {}", m.case, m.spectrum, b.spectrum);
    assert!(
        m.reconstruction <= b.reconstruction,
        "{kind} {}: reconstruction error {} ulp > {}",
        m.case, m.reconstruction, b.reconstruction
    );
    assert!(
        m.orthogonality <= b.orthogonality,
        "{kind} {}: orthogonality error {} ulp > {}",
        m.case, m.orthogonality, b.orthogonality
    );
}

// ============================================================================
// Gates
// ============================================================================

#[test]
fn svd_converges_to_the_references_on_every_case() {
    for (case, refs) in data::SVD {
        check("SVD", &measure_svd(case, refs), &BOUNDS.svd);
    }
}

#[test]
fn eigen_symmetric_converges_to_the_references_on_every_case() {
    for (case, refs) in data::EIGEN {
        check("EIGEN", &measure_eigen(case, refs), &BOUNDS.eigen);
    }
}

#[test]
fn schur_is_a_real_schur_form_with_the_reference_spectrum_on_every_case() {
    for (case, refs) in data::SCHUR {
        check("SCHUR", &measure_schur(case, refs), &BOUNDS.schur);
    }
}

/// The consumer's matvec through the SVD of their rank-6 matrix (reported at
/// realtime Q22.10: worst relative error 2.17 on 0.6.1, 0.146 on 0.4.x).
#[test]
fn consumer_matvec_through_the_svd() {
    let (case, _) = &data::SVD[0];
    assert_eq!(case.name, "rank6_8x8_consumer_report");
    let w = build(case);
    let tenth = FixedPoint::from_str("0.1");
    let mut x = FixedVector::new(8);
    for i in 0..8 {
        x[i] = tenth * FixedPoint::from_int(i as i32 + 1);
    }
    let direct = w.mul_vector(&x);
    let svd = svd_decompose(&w).expect("svd");
    let v = svd.vt.mul_vector(&x);
    let mut sv = FixedVector::new(8);
    for j in 0..8 {
        sv[j] = svd.sigma[j] * v[j];
    }
    let y = svd.u.mul_vector(&sv);
    let thousand = FixedPoint::from_int(1000);
    let mut worst_per_mille = FixedPoint::ZERO;
    for i in 0..8 {
        worst_per_mille = worst_per_mille.max((y[i] - direct[i]).abs() * thousand / direct[i].abs());
    }
    println!("consumer matvec: worst relative error {worst_per_mille} per mille");
    if let Some(bound) = BOUNDS.consumer_per_mille {
        assert!(
            worst_per_mille <= FixedPoint::from_int(bound),
            "consumer matvec relative error {worst_per_mille} per mille > {bound}"
        );
    }
}

/// `x (J - I)` with `x` a sixteenth of the storage maximum: every square of an
/// off-diagonal entry is far beyond storage (0.6.1's Jacobi convergence test
/// squared them at storage precision and wrapped). Exact spectrum `2x, -x, -x`;
/// singular values `2x, x, x`.
#[test]
fn large_entries_decompose_without_wrapping() {
    let x = half_max() / FixedPoint::from_int(8);
    let a = FixedMatrix::from_fn(3, 3, |i, j| if i == j { FixedPoint::ZERO } else { x });
    let two_x = x + x;

    let eig = eigen_symmetric(&a).expect("eigen_symmetric on large entries");
    let mut values: Vec<FixedPoint> = (0..3).map(|i| eig.values[i]).collect();
    values.sort();
    let eig_err = ulps(values[0] + x).max(ulps(values[1] + x)).max(ulps(values[2] - two_x));

    let svd = svd_decompose(&a).expect("svd_decompose on large entries");
    let svd_err = ulps(svd.sigma[0] - two_x).max(ulps(svd.sigma[1] - x)).max(ulps(svd.sigma[2] - x));

    let schur = schur_decompose(&a).expect("schur_decompose on large entries");
    assert_real_schur_form("large_entries", &schur.t);
    let mut diag: Vec<FixedPoint> = (0..3).map(|i| schur.t.get(i, i)).collect();
    diag.sort();
    let schur_err = ulps(diag[0] + x).max(ulps(diag[1] + x)).max(ulps(diag[2] - two_x));

    println!("large entries x = {x}: eigen {eig_err} ulp, svd {svd_err} ulp, schur {schur_err} ulp");
    for (kind, err) in [("eigen", eig_err), ("svd", svd_err), ("schur", schur_err)] {
        assert!(err <= BOUNDS.large_entries, "{kind} on large entries: {err} ulp > {}", BOUNDS.large_entries);
    }
}

/// Norms and entries beyond the storage range are `TierOverflow`, not a panic
/// and not a wrapped result.
#[test]
fn storage_overflow_is_an_error() {
    let h = half_max();
    let big = FixedMatrix::from_fn(6, 6, |_, _| h);
    assert_eq!(svd_decompose(&big).unwrap_err(), OverflowDetected::TierOverflow);
    assert_eq!(schur_decompose(&big).unwrap_err(), OverflowDetected::TierOverflow);
    // eigenvalue 3h of the 4x4 h (J - I) is 1.5 times the storage maximum
    let pattern = FixedMatrix::from_fn(4, 4, |i, j| if i == j { FixedPoint::ZERO } else { h });
    assert_eq!(eigen_symmetric(&pattern).unwrap_err(), OverflowDetected::TierOverflow);
}
