// ============================================================================
// TIER N+1 ARCTANGENT
// ============================================================================
//
// **ALGORITHM**: Argument reduction + Taylor series
//   1. If |x| > 1: atan(x) = sign(x)*π/2 - atan(1/x)
//   2. If |x| > tan(π/8) ≈ 0.414: atan(x) = π/4 + atan((x-1)/(x+1))
//   3. Core: Taylor series x - x³/3 + x⁵/5 - x⁷/7 + ...
//
// **PRECISION**: Matches other transcendentals (19/38/77 correct digits)
//
// ============================================================================

#[allow(unused_imports)]
use crate::fixed_point::i256::I256;
#[allow(unused_imports)]
use crate::fixed_point::i512::I512;
#[allow(unused_imports)]
use crate::fixed_point::i1024::I1024;
#[allow(unused_imports)]
use crate::fixed_point::I2048;

// Include trig constants generated by build.rs (shared with sin_cos)
// NOTE: These are already included in sin_cos_tier_n_plus_1.rs via include!()
// We re-use them via the module-level constants that are in scope.

// Reuse upscale/downscale helpers
#[allow(unused_imports)]
use super::exp_tier_n_plus_1::{
    upscale_q64_to_q128, upscale_q128_to_q256, upscale_q64_to_q256,
    downscale_q128_to_q64, downscale_q256_to_q128, downscale_q256_to_q64,
};

// Re-include trig constants (each .rs file gets its own scope)
#[cfg(feature = "rebuild-tables")]
include!(concat!(env!("OUT_DIR"), "/trig_constants.rs"));
#[cfg(not(feature = "rebuild-tables"))]
include!("../../../../generated_tables/trig_constants.rs");

// ============================================================================
// Q64.64 IMPLEMENTATION
// ============================================================================

#[cfg(table_format = "q64_64")]
pub fn atan_binary_i128(x: i128) -> i128 {
    atan_q64_64(x)
}

#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
pub fn atan_binary_i256(x: I256) -> I256 {
    // Tier N+1: compute atan at Q128.128 natively
    atan_q128_128(x)
}

#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
pub fn atan_binary_i512(x: I512) -> I512 {
    // Compute at Q256.256 for Q64.64/Q32.32 profile
    let x_q256 = x;
    atan_q256_256(x_q256)
}

/// atan2(y, x) — full quadrant arctangent in Q64.64
#[cfg(table_format = "q64_64")]
pub fn atan2_binary_i128(y: i128, x: i128) -> i128 {
    atan2_q64_64(y, x)
}

#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
pub fn atan2_binary_i256(y: I256, x: I256) -> I256 {
    // Tier N+1: compute atan2 at Q128.128 natively
    atan2_q128_128_for_embedded(y, x)
}

#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
pub fn atan2_binary_i512(y: I512, x: I512) -> I512 {
    // Downscale to Q128.128, compute, upscale back
    let y_q128 = (y >> 128).as_i256();
    let x_q128 = (x >> 128).as_i256();
    let result_q128 = atan2_q128_128_for_embedded(y_q128, x_q128);
    I512::from_i256(result_q128) << 128
}

#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
fn atan_q64_64(x: i128) -> i128 {
    let one_q64: i128 = 1i128 << 64;

    if x == 0 {
        return 0;
    }

    let is_neg = x < 0;
    let abs_x = if is_neg { -x } else { x };

    // Reduction 1: if |x| > 1, use atan(x) = π/2 - atan(1/x)
    // NOTE: Call atan_q64_64 recursively (not atan_core directly) so that
    // inv_x gets the tan(π/8) reduction too — ensures convergence for all inputs.
    if abs_x > one_q64 {
        // Compute 1/x in Q64.64
        let inv_x = {
            let one_wide = I256::from_i128(one_q64) << 64;
            let x_wide = I256::from_i128(abs_x);
            (one_wide / x_wide).as_i128()
        };
        let atan_inv = atan_q64_64(inv_x);
        let result = PI_HALF_Q64 - atan_inv;
        return if is_neg { -result } else { result };
    }

    // Reduction 2: if |x| > tan(π/8), use atan(x) = π/4 + atan((x-1)/(x+1))
    if abs_x > TAN_PI_8_Q64 {
        let num = abs_x - one_q64; // x - 1
        let den = abs_x + one_q64; // x + 1
        let reduced = {
            let num_wide = I256::from_i128(num) << 64;
            let den_wide = I256::from_i128(den);
            (num_wide / den_wide).as_i128()
        };
        let atan_reduced = atan_core_q64_64(reduced);
        let result = PI_QUARTER_Q64 + atan_reduced;
        return if is_neg { -result } else { result };
    }

    let result = atan_core_q64_64(abs_x);
    if is_neg { -result } else { result }
}

/// Core Taylor series for atan(x), |x| <= tan(π/8) ≈ 0.414
/// atan(x) = x - x³/3 + x⁵/5 - x⁷/7 + ...
#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
fn atan_core_q64_64(x: i128) -> i128 {
    let x_sq = {
        let x_wide = I256::from_i128(x);
        ((x_wide * x_wide) >> 64).as_i128()
    };

    // Horner form: atan(x) = x * (1 - x²/3 + x⁴/5 - x⁶/7 + ...)
    // = x * (1 - x²*(1/3 - x²*(1/5 - x²*(1/7 - ...))))
    // For Q64.64 (64 fractional bits), with |x_sq| ≤ 0.1716:
    // Need n such that 0.1716^n < 2^{-64} → n > 64*ln(2)/ln(1/0.1716) ≈ 25.2
    let num_terms = 27;
    let mut result: i128 = 0;

    // Build from inside out
    for k in (1..num_terms).rev() {
        let n = 2 * k + 1; // 3, 5, 7, ...
        // Coefficient: 1/n in Q64.64
        let coeff = (1i128 << 64) / (n as i128);
        let term = {
            let x_sq_wide = I256::from_i128(x_sq);
            let result_wide = I256::from_i128(result);
            ((x_sq_wide * result_wide) >> 64).as_i128()
        };
        result = coeff - term;
    }

    // Final: atan(x) = x * (1 - x² * result)
    let one_q64 = 1i128 << 64;
    let inner = {
        let x_sq_wide = I256::from_i128(x_sq);
        let result_wide = I256::from_i128(result);
        ((x_sq_wide * result_wide) >> 64).as_i128()
    };
    let poly = one_q64 - inner;

    let atan_val = {
        let x_wide = I256::from_i128(x);
        let poly_wide = I256::from_i128(poly);
        ((x_wide * poly_wide) >> 64).as_i128()
    };

    atan_val
}

/// atan2(y, x) in Q64.64 — handles all quadrants
#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
fn atan2_q64_64(y: i128, x: i128) -> i128 {
    if x == 0 && y == 0 {
        return 0; // undefined, return 0
    }

    if x > 0 {
        // atan(y/x)
        let ratio = {
            let y_wide = I256::from_i128(y) << 64;
            let x_wide = I256::from_i128(x);
            (y_wide / x_wide).as_i128()
        };
        return atan_q64_64(ratio);
    }

    if x < 0 && y >= 0 {
        // atan(y/x) + π
        let ratio = {
            let y_wide = I256::from_i128(y) << 64;
            let x_wide = I256::from_i128(x);
            (y_wide / x_wide).as_i128()
        };
        return atan_q64_64(ratio) + PI_Q64;
    }

    if x < 0 && y < 0 {
        // atan(y/x) - π
        let ratio = {
            let y_wide = I256::from_i128(y) << 64;
            let x_wide = I256::from_i128(x);
            (y_wide / x_wide).as_i128()
        };
        return atan_q64_64(ratio) - PI_Q64;
    }

    // x == 0
    if y > 0 {
        PI_HALF_Q64
    } else {
        -PI_HALF_Q64
    }
}

// ============================================================================
// Q128.128 IMPLEMENTATION
// ============================================================================

#[cfg(table_format = "q128_128")]
pub fn atan_binary_i128(x: i128) -> i128 {
    let x_q128 = upscale_q64_to_q128(x);
    downscale_q128_to_q64(atan_q128_128(x_q128))
}

#[cfg(table_format = "q128_128")]
pub fn atan_binary_i256(x: I256) -> I256 {
    // UGOD Tier N+1: Q128.128 storage → compute at Q256.256 → downscale
    let x_q256 = upscale_q128_to_q256(x);
    downscale_q256_to_q128(atan_q256_256_for_balanced(x_q256))
}

#[cfg(table_format = "q128_128")]
pub fn atan_binary_i512(x: I512) -> I512 {
    // Direct Q256.256 computation (compute tier for balanced profile)
    atan_q256_256_for_balanced(x)
}

#[cfg(table_format = "q128_128")]
pub fn atan2_binary_i128(y: i128, x: i128) -> i128 {
    let y_q128 = upscale_q64_to_q128(y);
    let x_q128 = upscale_q64_to_q128(x);
    downscale_q128_to_q64(atan2_q128_128(y_q128, x_q128))
}

#[cfg(table_format = "q128_128")]
pub fn atan2_binary_i256(y: I256, x: I256) -> I256 {
    // UGOD Tier N+1: Q128.128 storage → compute at Q256.256 → downscale
    let y_q256 = upscale_q128_to_q256(y);
    let x_q256 = upscale_q128_to_q256(x);
    downscale_q256_to_q128(atan2_q256_256_for_balanced(y_q256, x_q256))
}

#[cfg(table_format = "q128_128")]
pub fn atan2_binary_i512(y: I512, x: I512) -> I512 {
    // Direct Q256.256 computation (compute tier for balanced profile)
    atan2_q256_256_for_balanced(y, x)
}

#[cfg(any(table_format = "q64_64", table_format = "q128_128", table_format = "q32_32", table_format = "q16_16"))]
fn atan_q128_128(x: I256) -> I256 {
    let one_q128 = I256::from_i128(1) << 128;

    if x == I256::zero() {
        return I256::zero();
    }

    let is_neg = x < I256::zero();
    let abs_x = if is_neg { I256::zero() - x } else { x };

    if abs_x > one_q128 {
        let inv_x = {
            let one_wide = I512::from_i256(one_q128) << 128;
            let x_wide = I512::from_i256(abs_x);
            (one_wide / x_wide).as_i256()
        };
        let atan_inv = atan_q128_128(inv_x);
        let result = I256::from_words(PI_HALF_Q128) - atan_inv;
        return if is_neg { I256::zero() - result } else { result };
    }

    let tan_pi8 = I256::from_words(TAN_PI_8_Q128);
    if abs_x > tan_pi8 {
        let num = abs_x - one_q128;
        let den = abs_x + one_q128;
        let reduced = {
            let num_wide = I512::from_i256(num) << 128;
            let den_wide = I512::from_i256(den);
            (num_wide / den_wide).as_i256()
        };
        let atan_reduced = atan_core_q128_128(reduced);
        let result = I256::from_words(PI_QUARTER_Q128) + atan_reduced;
        return if is_neg { I256::zero() - result } else { result };
    }

    let result = atan_core_q128_128(abs_x);
    if is_neg { I256::zero() - result } else { result }
}

#[cfg(any(table_format = "q64_64", table_format = "q128_128", table_format = "q32_32", table_format = "q16_16"))]
fn atan_core_q128_128(x: I256) -> I256 {
    let x_sq = {
        let x_wide = I512::from_i256(x);
        ((x_wide * x_wide) >> 128).as_i256()
    };

    // For Q128.128 (128 fractional bits), with |x_sq| ≤ 0.1716:
    // Need n such that 0.1716^n < 2^{-128} → n > 128*ln(2)/ln(1/0.1716) ≈ 50.3
    let num_terms = 55;
    let mut result = I256::zero();

    for k in (1..num_terms).rev() {
        let n = 2 * k + 1;
        // 1/n in Q128.128
        let coeff = {
            let one_wide = I512::from_i256(I256::from_i128(1)) << 128;
            let n_wide = I512::from_i256(I256::from_i128(n as i128));
            (one_wide / n_wide).as_i256()
        };
        let term = {
            let x_sq_wide = I512::from_i256(x_sq);
            let result_wide = I512::from_i256(result);
            ((x_sq_wide * result_wide) >> 128).as_i256()
        };
        result = coeff - term;
    }

    let one_q128 = I256::from_i128(1) << 128;
    let inner = {
        let x_sq_wide = I512::from_i256(x_sq);
        let result_wide = I512::from_i256(result);
        ((x_sq_wide * result_wide) >> 128).as_i256()
    };
    let poly = one_q128 - inner;

    let x_wide = I512::from_i256(x);
    let poly_wide = I512::from_i256(poly);
    ((x_wide * poly_wide) >> 128).as_i256()
}

#[cfg(table_format = "q128_128")]
fn atan2_q128_128(y: I256, x: I256) -> I256 {
    let zero = I256::zero();
    if x == zero && y == zero {
        return zero;
    }

    if x > zero {
        let ratio = {
            let y_wide = I512::from_i256(y) << 128;
            let x_wide = I512::from_i256(x);
            (y_wide / x_wide).as_i256()
        };
        return atan_q128_128(ratio);
    }

    let pi = I256::from_words(PI_Q128);
    if x < zero && y >= zero {
        let ratio = {
            let y_wide = I512::from_i256(y) << 128;
            let x_wide = I512::from_i256(x);
            (y_wide / x_wide).as_i256()
        };
        return atan_q128_128(ratio) + pi;
    }

    if x < zero && y < zero {
        let ratio = {
            let y_wide = I512::from_i256(y) << 128;
            let x_wide = I512::from_i256(x);
            (y_wide / x_wide).as_i256()
        };
        return atan_q128_128(ratio) - pi;
    }

    let pi_half = I256::from_words(PI_HALF_Q128);
    if y > zero { pi_half } else { zero - pi_half }
}

// ============================================================================
// Q256.256 IMPLEMENTATION
// ============================================================================

#[cfg(table_format = "q256_256")]
pub fn atan_binary_i128(x: i128) -> i128 {
    let x_q256 = upscale_q64_to_q256(x);
    downscale_q256_to_q64(atan_q256_256(x_q256))
}

#[cfg(table_format = "q256_256")]
pub fn atan_binary_i256(x: I256) -> I256 {
    let x_q256 = upscale_q128_to_q256(x);
    downscale_q256_to_q128(atan_q256_256(x_q256))
}

#[cfg(table_format = "q256_256")]
pub fn atan_binary_i512(x: I512) -> I512 {
    atan_q256_256(x)
}

#[cfg(table_format = "q256_256")]
pub fn atan2_binary_i128(y: i128, x: i128) -> i128 {
    let y_q256 = upscale_q64_to_q256(y);
    let x_q256 = upscale_q64_to_q256(x);
    downscale_q256_to_q64(atan2_q256_256(y_q256, x_q256))
}

#[cfg(table_format = "q256_256")]
pub fn atan2_binary_i256(y: I256, x: I256) -> I256 {
    let y_q256 = upscale_q128_to_q256(y);
    let x_q256 = upscale_q128_to_q256(x);
    downscale_q256_to_q128(atan2_q256_256(y_q256, x_q256))
}

#[cfg(table_format = "q256_256")]
pub fn atan2_binary_i512(y: I512, x: I512) -> I512 {
    atan2_q256_256(y, x)
}

#[cfg(any(table_format = "q64_64", table_format = "q256_256", table_format = "q32_32", table_format = "q16_16"))]
fn atan_q256_256(x: I512) -> I512 {
    let one_q256 = I512::from_i128(1) << 256;

    if x == I512::zero() {
        return I512::zero();
    }

    let is_neg = x < I512::zero();
    let abs_x = if is_neg { I512::zero() - x } else { x };

    if abs_x > one_q256 {
        let inv_x = {
            let one_wide = I1024::from_i512(one_q256) << 256;
            let x_wide = I1024::from_i512(abs_x);
            (one_wide / x_wide).as_i512()
        };
        // Recurse through full reduction (inv_x < 1, so won't re-enter this branch)
        let atan_inv = atan_q256_256(inv_x);
        let result = I512::from_words(PI_HALF_Q256) - atan_inv;
        return if is_neg { I512::zero() - result } else { result };
    }

    let tan_pi8 = I512::from_words(TAN_PI_8_Q256);
    if abs_x > tan_pi8 {
        let num = abs_x - one_q256;
        let den = abs_x + one_q256;
        let reduced = {
            let num_wide = I1024::from_i512(num) << 256;
            let den_wide = I1024::from_i512(den);
            (num_wide / den_wide).as_i512()
        };
        let atan_reduced = atan_core_q256_256(reduced);
        let result = I512::from_words(PI_QUARTER_Q256) + atan_reduced;
        return if is_neg { I512::zero() - result } else { result };
    }

    let result = atan_core_q256_256(abs_x);
    if is_neg { I512::zero() - result } else { result }
}

#[cfg(any(table_format = "q64_64", table_format = "q256_256", table_format = "q32_32", table_format = "q16_16"))]
fn atan_core_q256_256(x: I512) -> I512 {
    let x_sq = {
        let x_wide = I1024::from_i512(x);
        ((x_wide * x_wide) >> 256).as_i512()
    };

    // For Q256.256 storage precision (256 fractional bits), with |x_sq| ≤ tan(π/8)² ≈ 0.1716:
    // Need n such that 0.1716^n < 2^{-256} → n > 256*ln(2)/ln(1/0.1716) ≈ 101
    let num_terms = 105;
    let mut result = I512::zero();

    for k in (1..num_terms).rev() {
        let n = 2 * k + 1;
        // 1/n in Q256.256
        let coeff = {
            let one_wide = I1024::from_i512(I512::from_i128(1)) << 256;
            let n_wide = I1024::from_i512(I512::from_i128(n as i128));
            (one_wide / n_wide).as_i512()
        };
        let term = {
            let x_sq_wide = I1024::from_i512(x_sq);
            let result_wide = I1024::from_i512(result);
            ((x_sq_wide * result_wide) >> 256).as_i512()
        };
        result = coeff - term;
    }

    let one_q256 = I512::from_i128(1) << 256;
    let inner = {
        let x_sq_wide = I1024::from_i512(x_sq);
        let result_wide = I1024::from_i512(result);
        ((x_sq_wide * result_wide) >> 256).as_i512()
    };
    let poly = one_q256 - inner;

    let x_wide = I1024::from_i512(x);
    let poly_wide = I1024::from_i512(poly);
    ((x_wide * poly_wide) >> 256).as_i512()
}

#[cfg(table_format = "q256_256")]
fn atan2_q256_256(y: I512, x: I512) -> I512 {
    let zero = I512::zero();
    if x == zero && y == zero {
        return zero;
    }

    if x > zero {
        let ratio = {
            let y_wide = I1024::from_i512(y) << 256;
            let x_wide = I1024::from_i512(x);
            (y_wide / x_wide).as_i512()
        };
        return atan_q256_256(ratio);
    }

    let pi = I512::from_words(PI_Q256);
    if x < zero && y >= zero {
        let ratio = {
            let y_wide = I1024::from_i512(y) << 256;
            let x_wide = I1024::from_i512(x);
            (y_wide / x_wide).as_i512()
        };
        return atan_q256_256(ratio) + pi;
    }

    if x < zero && y < zero {
        let ratio = {
            let y_wide = I1024::from_i512(y) << 256;
            let x_wide = I1024::from_i512(x);
            (y_wide / x_wide).as_i512()
        };
        return atan_q256_256(ratio) - pi;
    }

    let pi_half = I512::from_words(PI_HALF_Q256);
    if y > zero { pi_half } else { zero - pi_half }
}

// ============================================================================
// Q512.512 IMPLEMENTATION (I1024) — COMPUTE TIER FOR SCIENTIFIC PROFILE
// ============================================================================

#[cfg(table_format = "q256_256")]
pub fn atan_binary_i1024(x: I1024) -> I1024 {
    atan_q512_512(x)
}

#[cfg(table_format = "q256_256")]
pub fn atan2_binary_i1024(y: I1024, x: I1024) -> I1024 {
    atan2_q512_512(y, x)
}

#[cfg(table_format = "q256_256")]
fn atan_q512_512(x: I1024) -> I1024 {
    let one_q512 = I1024::from_i128(1) << 512;

    let is_neg = (x.words[15] & 0x8000_0000_0000_0000) != 0;
    let abs_x = if is_neg { I1024::zero() - x } else { x };

    // Reduction 1: If |x| > 1, atan(x) = π/2 - atan(1/x)
    if abs_x > one_q512 {
        let inv_x = {
            use crate::fixed_point::domains::binary_fixed::i2048::i2048_div;
            let one_wide = I2048::from_i1024(one_q512) << 512;
            let x_wide = I2048::from_i1024(abs_x);
            i2048_div(one_wide, x_wide).as_i1024()
        };
        // Recurse through full reduction (inv_x < 1, so won't re-enter this branch)
        let atan_inv = atan_q512_512(inv_x);
        let result = I1024::from_words(PI_HALF_Q512) - atan_inv;
        return if is_neg { I1024::zero() - result } else { result };
    }

    // Reduction 2: If |x| > tan(π/8), atan(x) = π/4 + atan((x-1)/(x+1))
    let tan_pi8 = I1024::from_words(TAN_PI_8_Q512);
    if abs_x > tan_pi8 {
        let num = abs_x - one_q512;
        let den = abs_x + one_q512;
        let reduced = {
            use crate::fixed_point::domains::binary_fixed::i2048::i2048_div;
            let num_wide = I2048::from_i1024(num) << 512;
            let den_wide = I2048::from_i1024(den);
            i2048_div(num_wide, den_wide).as_i1024()
        };
        let atan_reduced = atan_core_q512_512(reduced);
        let result = I1024::from_words(PI_QUARTER_Q512) + atan_reduced;
        return if is_neg { I1024::zero() - result } else { result };
    }

    // Fallback: |x| <= tan(π/8), call core directly
    let result = atan_core_q512_512(abs_x);
    if is_neg { I1024::zero() - result } else { result }
}

#[cfg(table_format = "q256_256")]
fn atan_core_q512_512(x: I1024) -> I1024 {
    use super::ln_tier_n_plus_1::multiply_i1024_q512_512;

    // x is abs(input) from atan_q512_512, should be positive,
    // but use signed multiply for safety (Horner intermediate results can be negative)
    let x_sq = multiply_i1024_q512_512(x, x);

    // For Q512.512 (512 fractional bits), with |x_sq| ≤ 0.1716:
    // Need n such that 0.1716^n < 2^{-512} → n > 512*ln(2)/ln(1/0.1716) ≈ 201
    let num_terms = 210;
    let mut result = I1024::zero();

    for k in (1..num_terms).rev() {
        // Coefficient 1/(2k+1) computed inline
        let n = (2 * k + 1) as i128;
        let coeff = {
            use crate::fixed_point::domains::binary_fixed::i2048::i2048_div;
            let one_shifted = I2048::from_i1024(I1024::from_i128(1)) << 512;
            let n_wide = I2048::from_i1024(I1024::from_i128(n));
            i2048_div(one_shifted, n_wide).as_i1024()
        };

        // SIGNED multiply: result can be negative in Horner scheme
        let term = multiply_i1024_q512_512(x_sq, result);

        result = coeff - term;
    }

    // Final: atan(x) = x * (1 - x² * result)
    let one_q512 = I1024::from_i128(1) << 512;
    let inner = multiply_i1024_q512_512(x_sq, result);
    let poly = one_q512 - inner;

    // SIGNED multiply: x could theoretically be negative (from reduced argument)
    multiply_i1024_q512_512(x, poly)
}

#[cfg(table_format = "q256_256")]
fn atan2_q512_512(y: I1024, x: I1024) -> I1024 {
    let zero = I1024::zero();
    if x == zero && y == zero {
        return zero;
    }

    if x > zero {
        let ratio = {
            use crate::fixed_point::domains::binary_fixed::i2048::i2048_div;
            let y_wide = I2048::from_i1024(y) << 512;
            let x_wide = I2048::from_i1024(x);
            i2048_div(y_wide, x_wide).as_i1024()
        };
        return atan_q512_512(ratio);
    }

    let pi = I1024::from_words(PI_Q512);
    let y_is_neg = (y.words[15] & 0x8000_0000_0000_0000) != 0;
    let x_is_neg = (x.words[15] & 0x8000_0000_0000_0000) != 0;

    if x_is_neg && !y_is_neg {
        let ratio = {
            use crate::fixed_point::domains::binary_fixed::i2048::i2048_div;
            let y_wide = I2048::from_i1024(y) << 512;
            let x_wide = I2048::from_i1024(x);
            i2048_div(y_wide, x_wide).as_i1024()
        };
        return atan_q512_512(ratio) + pi;
    }

    if x_is_neg && y_is_neg {
        let ratio = {
            use crate::fixed_point::domains::binary_fixed::i2048::i2048_div;
            let y_wide = I2048::from_i1024(y) << 512;
            let x_wide = I2048::from_i1024(x);
            i2048_div(y_wide, x_wide).as_i1024()
        };
        return atan_q512_512(ratio) - pi;
    }

    let pi_half = I1024::from_words(PI_HALF_Q512);
    if !y_is_neg { pi_half } else { zero - pi_half }
}

// ============================================================================
// COMPUTE-TIER DISPATCH FUNCTIONS
// ============================================================================

/// Compute atan at compute tier for scientific profile
#[cfg(table_format = "q256_256")]
pub fn atan_compute_tier_i1024(x: I1024) -> I1024 {
    atan_binary_i1024(x)
}

/// Compute atan2 at compute tier for scientific profile
#[cfg(table_format = "q256_256")]
pub fn atan2_compute_tier_i1024(y: I1024, x: I1024) -> I1024 {
    atan2_binary_i1024(y, x)
}

/// Compute atan at compute tier for balanced profile (Q256.256 on I512)
#[cfg(table_format = "q128_128")]
pub fn atan_compute_tier_i512(x: I512) -> I512 {
    atan_q256_256_for_balanced(x)
}

/// Compute atan2 at compute tier for balanced profile
#[cfg(table_format = "q128_128")]
pub fn atan2_compute_tier_i512(y: I512, x: I512) -> I512 {
    atan2_q256_256_for_balanced(y, x)
}

/// Compute atan at compute tier for embedded/performance profile (Q128.128 on I256)
#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
pub fn atan_compute_tier_i256(x: I256) -> I256 {
    atan_q128_128_for_embedded(x)
}

/// Compute atan2 at compute tier for embedded/performance profile
#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
pub fn atan2_compute_tier_i256(y: I256, x: I256) -> I256 {
    atan2_q128_128_for_embedded(y, x)
}

// ============================================================================
// CROSS-PROFILE IMPLEMENTATIONS
// ============================================================================

// Q128.128 atan available under q64_64 for tier N+1

#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
fn atan_q128_128_for_embedded(x: I256) -> I256 {
    let one_q128 = I256::from_i128(1) << 128;

    let is_neg = x < I256::zero();
    let abs_x = if is_neg { I256::zero() - x } else { x };

    if abs_x > one_q128 {
        let inv_x = {
            let one_wide = I512::from_i256(one_q128) << 128;
            let x_wide = I512::from_i256(abs_x);
            (one_wide / x_wide).as_i256()
        };
        let atan_inv = atan_q128_128_for_embedded(inv_x);
        let result = I256::from_words(PI_HALF_Q128) - atan_inv;
        return if is_neg { I256::zero() - result } else { result };
    }

    let tan_pi8 = I256::from_words(TAN_PI_8_Q128);
    if abs_x > tan_pi8 {
        let num = abs_x - one_q128;
        let den = abs_x + one_q128;
        let reduced = {
            let num_wide = I512::from_i256(num) << 128;
            let den_wide = I512::from_i256(den);
            (num_wide / den_wide).as_i256()
        };
        let atan_reduced = atan_core_q128_128_impl(reduced);
        let result = I256::from_words(PI_QUARTER_Q128) + atan_reduced;
        return if is_neg { I256::zero() - result } else { result };
    }

    let result = atan_core_q128_128_impl(abs_x);
    if is_neg { I256::zero() - result } else { result }
}

#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
fn atan_core_q128_128_impl(x: I256) -> I256 {
    let x_sq = {
        let x_wide = I512::from_i256(x);
        ((x_wide * x_wide) >> 128).as_i256()
    };

    let num_terms = 33;
    let mut result = I256::zero();

    for k in (1..num_terms).rev() {
        let n = (2 * k + 1) as i128;
        let coeff = {
            let one_shifted = I512::from_i256(I256::from_i128(1)) << 128;
            let n_wide = I512::from_i256(I256::from_i128(n));
            (one_shifted / n_wide).as_i256()
        };
        let term = {
            let x_sq_wide = I512::from_i256(x_sq);
            let result_wide = I512::from_i256(result);
            ((x_sq_wide * result_wide) >> 128).as_i256()
        };
        result = coeff - term;
    }

    let one_q128 = I256::from_i128(1) << 128;
    let inner = {
        let x_sq_wide = I512::from_i256(x_sq);
        let result_wide = I512::from_i256(result);
        ((x_sq_wide * result_wide) >> 128).as_i256()
    };
    let poly = one_q128 - inner;

    let x_wide = I512::from_i256(x);
    let poly_wide = I512::from_i256(poly);
    ((x_wide * poly_wide) >> 128).as_i256()
}

#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
fn atan2_q128_128_for_embedded(y: I256, x: I256) -> I256 {
    let zero = I256::zero();
    if x == zero && y == zero { return zero; }
    if x > zero {
        let ratio = {
            let y_wide = I512::from_i256(y) << 128;
            let x_wide = I512::from_i256(x);
            (y_wide / x_wide).as_i256()
        };
        return atan_q128_128_for_embedded(ratio);
    }
    let pi = I256::from_words(PI_Q128);
    if x < zero && y >= zero {
        let ratio = {
            let y_wide = I512::from_i256(y) << 128;
            let x_wide = I512::from_i256(x);
            (y_wide / x_wide).as_i256()
        };
        return atan_q128_128_for_embedded(ratio) + pi;
    }
    if x < zero && y < zero {
        let ratio = {
            let y_wide = I512::from_i256(y) << 128;
            let x_wide = I512::from_i256(x);
            (y_wide / x_wide).as_i256()
        };
        return atan_q128_128_for_embedded(ratio) - pi;
    }
    let pi_half = I256::from_words(PI_HALF_Q128);
    if y > zero { pi_half } else { zero - pi_half }
}

// Q256.256 atan available under q128_128 for tier N+1

#[cfg(table_format = "q128_128")]
fn atan_q256_256_for_balanced(x: I512) -> I512 {
    let one_q256 = I512::from_i128(1) << 256;

    if x == I512::zero() { return I512::zero(); }

    let is_neg = x < I512::zero();
    let abs_x = if is_neg { I512::zero() - x } else { x };

    if abs_x > one_q256 {
        let inv_x = {
            let one_wide = I1024::from_i512(one_q256) << 256;
            let x_wide = I1024::from_i512(abs_x);
            (one_wide / x_wide).as_i512()
        };
        // Recurse through full reduction (inv_x < 1, so won't re-enter this branch)
        let atan_inv = atan_q256_256_for_balanced(inv_x);
        let result = I512::from_words(PI_HALF_Q256) - atan_inv;
        return if is_neg { I512::zero() - result } else { result };
    }

    let tan_pi8 = I512::from_words(TAN_PI_8_Q256);
    if abs_x > tan_pi8 {
        let num = abs_x - one_q256;
        let den = abs_x + one_q256;
        let reduced = {
            let num_wide = I1024::from_i512(num) << 256;
            let den_wide = I1024::from_i512(den);
            (num_wide / den_wide).as_i512()
        };
        let atan_reduced = atan_core_q256_256_impl(reduced);
        let result = I512::from_words(PI_QUARTER_Q256) + atan_reduced;
        return if is_neg { I512::zero() - result } else { result };
    }

    let result = atan_core_q256_256_impl(abs_x);
    if is_neg { I512::zero() - result } else { result }
}

#[cfg(table_format = "q128_128")]
fn atan_core_q256_256_impl(x: I512) -> I512 {
    let x_sq = {
        let x_wide = I1024::from_i512(x);
        ((x_wide * x_wide) >> 256).as_i512()
    };

    let num_terms = 65;
    let mut result = I512::zero();

    for k in (1..num_terms).rev() {
        let n = (2 * k + 1) as i128;
        let coeff = {
            let one_shifted = I1024::from_i512(I512::from_i128(1)) << 256;
            let n_wide = I1024::from_i512(I512::from_i128(n));
            (one_shifted / n_wide).as_i512()
        };
        let term = {
            let x_sq_wide = I1024::from_i512(x_sq);
            let result_wide = I1024::from_i512(result);
            ((x_sq_wide * result_wide) >> 256).as_i512()
        };
        result = coeff - term;
    }

    let one_q256 = I512::from_i128(1) << 256;
    let inner = {
        let x_sq_wide = I1024::from_i512(x_sq);
        let result_wide = I1024::from_i512(result);
        ((x_sq_wide * result_wide) >> 256).as_i512()
    };
    let poly = one_q256 - inner;

    let x_wide = I1024::from_i512(x);
    let poly_wide = I1024::from_i512(poly);
    ((x_wide * poly_wide) >> 256).as_i512()
}

#[cfg(table_format = "q128_128")]
fn atan2_q256_256_for_balanced(y: I512, x: I512) -> I512 {
    let zero = I512::zero();
    if x == zero && y == zero { return zero; }
    if x > zero {
        let ratio = {
            let y_wide = I1024::from_i512(y) << 256;
            let x_wide = I1024::from_i512(x);
            (y_wide / x_wide).as_i512()
        };
        return atan_q256_256_for_balanced(ratio);
    }
    let pi = I512::from_words(PI_Q256);
    if x < zero && y >= zero {
        let ratio = {
            let y_wide = I1024::from_i512(y) << 256;
            let x_wide = I1024::from_i512(x);
            (y_wide / x_wide).as_i512()
        };
        return atan_q256_256_for_balanced(ratio) + pi;
    }
    if x < zero && y < zero {
        let ratio = {
            let y_wide = I1024::from_i512(y) << 256;
            let x_wide = I1024::from_i512(x);
            (y_wide / x_wide).as_i512()
        };
        return atan_q256_256_for_balanced(ratio) - pi;
    }
    let pi_half = I512::from_words(PI_HALF_Q256);
    if y > zero { pi_half } else { zero - pi_half }
}

// ============================================================================
// Q32.32 / Q16.16 PROFILE WRAPPERS (i64 storage)
// ============================================================================

/// atan() for Q32.32 storage (i64) — tier N+1 via Q64.64
#[cfg(any(table_format = "q32_32", table_format = "q16_16"))]
pub fn atan_binary_i64(x: i64) -> i64 {
    use super::exp_tier_n_plus_1::{upscale_q32_to_q64, downscale_q64_to_q32};
    let x_q64 = upscale_q32_to_q64(x);
    let result_q64 = atan_q64_64(x_q64);
    downscale_q64_to_q32(result_q64)
}

/// atan() at compute tier for Q16.16 profile (Q32.32 on i64)
#[cfg(any(table_format = "q32_32", table_format = "q16_16"))]
pub fn atan_compute_tier_i64(x: i64) -> i64 {
    use super::exp_tier_n_plus_1::{upscale_q32_to_q64, downscale_q64_to_q32};
    let x_q64 = upscale_q32_to_q64(x);
    let result_q64 = atan_q64_64(x_q64);
    downscale_q64_to_q32(result_q64)
}

/// atan2() at compute tier for Q16.16 profile (Q32.32 on i64)
#[cfg(any(table_format = "q32_32", table_format = "q16_16"))]
pub fn atan2_compute_tier_i64(y: i64, x: i64) -> i64 {
    use super::exp_tier_n_plus_1::{upscale_q32_to_q64, downscale_q64_to_q32};
    let y_q64 = upscale_q32_to_q64(y);
    let x_q64 = upscale_q32_to_q64(x);
    let result_q64 = atan2_q64_64(y_q64, x_q64);
    downscale_q64_to_q32(result_q64)
}

/// atan() for Q32.32 profile — i128 is the compute tier (Q64.64)
#[cfg(any(table_format = "q32_32", table_format = "q16_16"))]
pub fn atan_binary_i128(x: i128) -> i128 {
    atan_q64_64(x)
}

/// atan2() for Q32.32 profile — i128 is the compute tier (Q64.64)
#[cfg(any(table_format = "q32_32", table_format = "q16_16"))]
pub fn atan2_binary_i128(y: i128, x: i128) -> i128 {
    atan2_q64_64(y, x)
}
