// ============================================================================
// TIER N+1 NATURAL LOGARITHM
// ============================================================================
//
// **PRINCIPLE**: Compute at tier N+1, downscale to tier N with ZERO precision loss
//
// **GUARANTEE**: ALL fractional bits of storage tier are 100% accurate
//
// **ALGORITHM**:
//   ln(x) = ln(2^k × m) where x > 0, m ∈ [1, 2), k = floor(log2(x))
//        = k × ln(2) + ln(m)
//        = k × ln(2) + ln(1 + (m-1))
//        = k × ln(2) + [table lookups] + taylor_series(remainder)
//
// **STRATEGY**:
//   - Tier 3 storage (i128/Q64.64):   Compute at Tier 4 (I256/Q128.128) → 19 decimals exact
//   - Tier 4 storage (I256/Q128.128): Compute at Tier 5 (I512/Q256.256) → 38 decimals exact
//   - Tier 5 storage (I512/Q256.256): Compute at Tier 6 (I1024/Q512.512) → 77 decimals exact
//
// **PRECISION IMPROVEMENT**:
//   - Native tier N: ~10-13 correct digits, error ~1e-11
//   - Tier N+1:      19 correct digits (Q64.64), error ~1e-19
//   - Improvement:   8 orders of magnitude reduction in error
//
// **PERFORMANCE COST**:
//   - Tier N+1: 3-4x slower than native
//   - Tier N+2: 10-15x slower than native
//   - Acceptable cost for full storage-tier accuracy
//
// ============================================================================

use crate::fixed_point::i256::I256;
use crate::fixed_point::i512::I512;
use crate::fixed_point::i1024::I1024;

// ============================================================================
// TABLE INCLUDES - Generated by build.rs
// ============================================================================

// Include ALL table sets for tier N+1 strategy (profile-aware compilation)
// Pre-built tables in src/generated_tables/; regenerate with --features rebuild-tables
#[cfg(feature = "rebuild-tables")]
include!(concat!(env!("OUT_DIR"), "/ln_q64_64_tables.rs"));
#[cfg(not(feature = "rebuild-tables"))]
include!("../../../../generated_tables/ln_q64_64_tables.rs");

#[cfg(feature = "rebuild-tables")]
include!(concat!(env!("OUT_DIR"), "/ln_q128_128_tables.rs"));
#[cfg(not(feature = "rebuild-tables"))]
include!("../../../../generated_tables/ln_q128_128_tables.rs");

#[cfg(feature = "rebuild-tables")]
include!(concat!(env!("OUT_DIR"), "/ln_q256_256_tables.rs"));
#[cfg(not(feature = "rebuild-tables"))]
include!("../../../../generated_tables/ln_q256_256_tables.rs");

#[cfg(feature = "rebuild-tables")]
include!(concat!(env!("OUT_DIR"), "/ln_q512_512_tables.rs"));
#[cfg(not(feature = "rebuild-tables"))]
include!("../../../../generated_tables/ln_q512_512_tables.rs");

// ============================================================================
// HELPER: Find MSB position (floor of log2)
// ============================================================================

/// Find the position of the most significant bit (0-indexed from LSB)
/// Returns None for x == 0
#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
#[inline(always)]
fn find_msb_position_i128(x: i128) -> Option<u32> {
    if x <= 0 {
        return None;
    }
    // 128 - 1 - leading_zeros gives position of MSB
    Some(127 - (x as u128).leading_zeros())
}

#[cfg(any(table_format = "q64_64", table_format = "q128_128", table_format = "q32_32", table_format = "q16_16"))]
#[inline(always)]
fn find_msb_position_i256(x: &I256) -> Option<u32> {
    if *x <= I256::zero() {
        return None;
    }
    // Check words from high to low
    for i in (0..4).rev() {
        if x.words[i] != 0 {
            let bit_pos = 63 - x.words[i].leading_zeros();
            return Some(i as u32 * 64 + bit_pos);
        }
    }
    None
}

#[cfg(any(table_format = "q128_128", table_format = "q256_256"))]
#[inline(always)]
fn find_msb_position_i512(x: &I512) -> Option<u32> {
    if *x <= I512::zero() {
        return None;
    }
    // Check words from high to low
    for i in (0..8).rev() {
        if x.words[i] != 0 {
            let bit_pos = 63 - x.words[i].leading_zeros();
            return Some(i as u32 * 64 + bit_pos);
        }
    }
    None
}

#[cfg(any(table_format = "q256_256", table_format = "q512_512"))]
#[inline(always)]
fn find_msb_position_i1024(x: &I1024) -> Option<u32> {
    if *x <= I1024::zero() {
        return None;
    }
    // Check words from high to low
    for i in (0..16).rev() {
        if x.words[i] != 0 {
            let bit_pos = 63 - x.words[i].leading_zeros();
            return Some(i as u32 * 64 + bit_pos);
        }
    }
    None
}

// ============================================================================
// TIER-NATIVE IMPLEMENTATIONS (Use tables at native precision)
// ============================================================================

/// Q64.64 native natural logarithm (Tier 3 baseline)
///
/// **INPUT**: i128 value in Q64.64 format (must be positive)
/// **OUTPUT**: i128 value in Q64.64 format
/// **PRECISION**: ~10-13 correct digits (baseline implementation)
/// **TABLES**: Uses Q64.64 tables directly (no conversion)
/// **DOMAIN**: x > 0 (returns i128::MIN for x <= 0)
#[inline(always)]
#[cfg(any(table_format = "q64_64", table_format = "q32_32", table_format = "q16_16"))]
pub fn ln_q64_64_native(x: i128) -> i128 {
    use crate::fixed_point::multiply_binary_i128;
    use crate::fixed_point::i256::I256;

    // Handle domain error: ln(x) undefined for x <= 0
    if x <= 0 {
        return i128::MIN; // Signal error
    }

    // Handle ln(1) = 0
    let one_q64 = 1i128 << 64;
    if x == one_q64 {
        return 0;
    }

    // Step 1: Range reduction - find k such that x = 2^k × m where m ∈ [1, 2)
    let msb_pos = find_msb_position_i128(x).unwrap_or(0);
    let k = msb_pos as i128 - 64;

    // Step 2: Normalize to get m = x / 2^k in Q64.64 format (m ∈ [1, 2))
    let m = if k >= 0 {
        x >> k
    } else {
        x << (-k)
    };

    // Step 3: Compute k × ln(2)
    let (ln2_main, ln2_comp) = LN_2_CONSTANT_TIER_3;
    let ln2 = ln2_main + ((ln2_comp as i128) >> 32);
    let k_ln2 = multiply_binary_i128(k << 64, ln2);

    // Step 4: y = m - 1, where y ∈ [0, 1)
    let y = m - one_q64;

    if y == 0 {
        return k_ln2;
    }

    // =========================================================================
    // MULTIPLICATIVE DECOMPOSITION (matches Q128.128+ algorithm)
    //
    // Identity: (1+y) = (1+a₁)(1+r₁) → ln(1+y) = ln(1+a₁) + ln(1+r₁)
    // where r₁ = (y - a₁) / (1 + a₁) — the TRUE mathematical remainder
    //
    // Each stage: extract top 10 bits of remainder, table lookup, divide to
    // get the next (smaller) remainder. After 4 stages, |r₄| < 2^-40.
    // =========================================================================

    // Division helper: a/b in Q64.64, using I256 intermediate for full precision
    #[inline(always)]
    fn divide_q64(a: i128, b: i128) -> i128 {
        if b == 0 { return 0; }
        let a_wide = I256::from_i128(a) << 64usize;
        let b_wide = I256::from_i128(b);
        (a_wide / b_wide).as_i128()
    }

    // Stage 1: Primary table lookup
    let k_idx = (y >> 54) as usize;  // Top 10 bits of y
    let (t1_main, t1_comp) = LN_PRIMARY_TABLE_TIER_3[k_idx];
    let ln_t1 = t1_main + ((t1_comp as i128) >> 32);

    // Multiplicative remainder: r₁ = (y - k/1024) / (1 + k/1024)
    let k_frac = (k_idx as i128) << 54;  // k/1024 in Q64.64
    let d1 = one_q64 + k_frac;
    let r1 = if k_idx == 0 { y } else { divide_q64(y - k_frac, d1) };

    // Stage 2: Secondary table lookup on r₁
    // r₁ < 1/1024, so top 10 bits are 0; extract bits [53..44]
    let j_idx = ((r1 >> 44) & 0x3FF) as usize;
    let (t2_main, t2_comp) = LN_SECONDARY_TABLE_TIER_3[j_idx];
    let ln_t2 = t2_main + ((t2_comp as i128) >> 32);

    let j_frac = (j_idx as i128) << 44;  // j/2^20 in Q64.64
    let d2 = one_q64 + j_frac;
    let r2 = if j_idx == 0 { r1 } else { divide_q64(r1 - j_frac, d2) };

    // Stage 3: Tertiary table lookup on r₂
    // r₂ < 1/2^20; extract bits [33..24]
    let m_idx = ((r2 >> 34) & 0x3FF) as usize;
    let (t3_main, t3_comp) = LN_TERTIARY_TABLE_TIER_3[m_idx];
    let ln_t3 = t3_main + ((t3_comp as i128) >> 32);

    let m_frac = (m_idx as i128) << 34;  // m/2^30 in Q64.64
    let d3 = one_q64 + m_frac;
    let r3 = if m_idx == 0 { r2 } else { divide_q64(r2 - m_frac, d3) };

    // Stage 4: Quaternary table lookup on r₃
    // r₃ < 1/2^30; extract bits [23..14]
    let p_idx = ((r3 >> 24) & 0x3FF) as usize;
    let (t4_main, t4_comp) = LN_QUATERNARY_TABLE_TIER_3[p_idx];
    let ln_t4 = t4_main + ((t4_comp as i128) >> 32);

    let p_frac = (p_idx as i128) << 24;  // p/2^40 in Q64.64
    let d4 = one_q64 + p_frac;
    let r4 = if p_idx == 0 { r3 } else { divide_q64(r3 - p_frac, d4) };

    // Step 6: Taylor series for final remainder (|r₄| < 2^-40)
    // ln(1 + r) ≈ r - r²/2 for |r| < 2^-40 (r³ < 2^-120, negligible for Q64.64)
    let ln_remainder = if r4 == 0 {
        0
    } else {
        let r2 = multiply_binary_i128(r4, r4);
        r4 - (r2 >> 1)
    };

    // Step 7: Combine: ln(x) = k×ln(2) + ln(1+a₁) + ln(1+a₂) + ln(1+a₃) + ln(1+a₄) + ln(1+r₄)
    k_ln2 + ln_t1 + ln_t2 + ln_t3 + ln_t4 + ln_remainder
}

/// Q128.128 native natural logarithm (Tier 4)
///
/// **INPUT**: I256 value in Q128.128 format (must be positive)
/// **OUTPUT**: I256 value in Q128.128 format
/// **PRECISION**: ~20-38 correct digits
/// **TABLES**: Uses Q128.128 tables with proper multiplicative decomposition
///
/// **ALGORITHM** (multiplicative, 4-stage decomposition):
/// For ln(1 + y) where y ∈ [0, 1):
/// 1. Primary lookup: ln(1 + k/1024) where k = floor(y * 1024)
/// 2. Compute scaled remainder: r1 = (y - k/1024) / (1 + k/1024)
/// 3. Secondary lookup on r1: ln(1 + j/2^20) where j = floor(r1 * 2^20)
/// 4. Compute scaled remainder: r2 = (r1 - j/2^20) / (1 + j/2^20)
/// 5. Tertiary lookup on r2: ln(1 + m/2^30) where m = floor(r2 * 2^30)
/// 6. Compute scaled remainder: r3 = (r2 - m/2^30) / (1 + m/2^30)
/// 7. Quaternary lookup on r3: ln(1 + p/2^40) where p = floor(r3 * 2^40)
/// 8. Taylor series on final remainder (|r4| < 2^-40, only 5 terms needed)
/// 9. Add all terms
#[inline(always)]
#[cfg(any(table_format = "q64_64", table_format = "q128_128", table_format = "q32_32", table_format = "q16_16"))]
pub fn ln_q128_128_native(x: I256) -> I256 {
    // Handle domain error: ln(x) undefined for x <= 0
    if x <= I256::zero() {
        return I256::min_value();
    }

    let one_q128 = I256::from_i128(1) << 128;
    if x == one_q128 {
        return I256::zero();
    }

    // Range reduction: find k such that x = 2^k × m where m ∈ [1, 2)
    let msb_pos = find_msb_position_i256(&x).unwrap_or(0);
    let k = msb_pos as i128 - 128;

    // Normalize to get m ∈ [1, 2)
    let m = if k >= 0 {
        x >> (k as u32)
    } else {
        x << ((-k) as usize)
    };

    // k × ln(2) with compensation
    let (ln2_main, ln2_comp) = LN_2_CONSTANT_TIER_4;
    let ln2 = ln2_main + I256::from_i128(ln2_comp >> 64);
    let k_i256 = I256::from_i128(k) << 128;
    let k_ln2 = multiply_i256_q128_128(k_i256, ln2);

    // y = m - 1, where y ∈ [0, 1)
    let y = m - one_q128;
    if y == I256::zero() {
        return k_ln2;
    }

    // =========================================================================
    // STAGE 1: Primary table lookup for ln(1 + k_idx/1024)
    // =========================================================================
    let y_u128 = y.as_u128();
    let k_idx = (y_u128 >> 118) as usize;

    let (t1_main, t1_comp) = LN_PRIMARY_TABLE_TIER_4[k_idx];
    let ln_t1 = t1_main + I256::from_i128(t1_comp >> 64);

    // Compute divisor: d1 = 1 + k_idx/1024 in Q128.128
    let k_frac = I256::from_i128(k_idx as i128) << 118; // k/1024 in Q128.128
    let d1 = one_q128 + k_frac;

    // Compute y - k/1024
    let y_minus_k = y - k_frac;

    // Compute r1 = (y - k/1024) / (1 + k/1024) — multiplicative decomposition
    let r1 = if y_minus_k == I256::zero() || k_idx == 0 {
        y_minus_k
    } else {
        divide_i256_q128_128(y_minus_k, d1)
    };

    // =========================================================================
    // STAGE 2: Secondary table lookup for ln(1 + j/2^20)
    // =========================================================================
    let r1_u128 = r1.as_u128();
    // r1 < 1/1024 = 2^-10, so bits 127..118 are 0; extract NEXT 10 bits (117..108)
    let j_idx = ((r1_u128 >> 108) & 0x3FF) as usize;

    let (t2_main, t2_comp) = LN_SECONDARY_TABLE_TIER_4[j_idx];
    let ln_t2 = t2_main + I256::from_i128(t2_comp >> 64);

    // j/2^20 in Q128.128 = j << 108
    let j_frac = I256::from_i128(j_idx as i128) << 108;
    let d2 = one_q128 + j_frac;
    let r1_minus_j = r1 - j_frac;

    let r2 = if r1_minus_j == I256::zero() || j_idx == 0 {
        r1_minus_j
    } else {
        divide_i256_q128_128(r1_minus_j, d2)
    };

    // =========================================================================
    // STAGE 3: Tertiary table lookup for ln(1 + m_idx/2^30)
    // =========================================================================
    let r2_u128 = r2.as_u128();
    // r2 < 1/2^20, so bits 127..108 are 0; extract NEXT 10 bits (107..98)
    let m_idx = ((r2_u128 >> 98) & 0x3FF) as usize;

    let (t3_main, t3_comp) = LN_TERTIARY_TABLE_TIER_4[m_idx];
    let ln_t3 = t3_main + I256::from_i128(t3_comp >> 64);

    // m/2^30 in Q128.128 = m << 98
    let m_frac = I256::from_i128(m_idx as i128) << 98;
    let d3 = one_q128 + m_frac;
    let r2_minus_m = r2 - m_frac;

    let r3 = if r2_minus_m == I256::zero() || m_idx == 0 {
        r2_minus_m
    } else {
        divide_i256_q128_128(r2_minus_m, d3)
    };

    // =========================================================================
    // STAGE 4: Quaternary table lookup for ln(1 + p_idx/2^40)
    // =========================================================================
    let r3_u128 = r3.as_u128();
    // r3 < 1/2^30, so bits 127..98 are 0; extract NEXT 10 bits (97..88)
    let p_idx = ((r3_u128 >> 88) & 0x3FF) as usize;

    let (t4_main, t4_comp) = LN_QUATERNARY_TABLE_TIER_4[p_idx];
    let ln_t4 = t4_main + I256::from_i128(t4_comp >> 64);

    // p/2^40 in Q128.128 = p << 88
    let p_frac = I256::from_i128(p_idx as i128) << 88;
    let d4 = one_q128 + p_frac;
    let r3_minus_p = r3 - p_frac;

    let r4 = if r3_minus_p == I256::zero() || p_idx == 0 {
        r3_minus_p
    } else {
        divide_i256_q128_128(r3_minus_p, d4)
    };

    // =========================================================================
    // STAGE 5: Taylor series for ln(1 + r4) where |r4| < 2^-40
    // =========================================================================
    let ln_remainder = taylor_series_ln_i256_q128_128(&r4);

    // Combine all parts
    k_ln2 + ln_t1 + ln_t2 + ln_t3 + ln_t4 + ln_remainder
}

/// Q256.256 native natural logarithm (Tier 5)
///
/// **INPUT**: I512 value in Q256.256 format (must be positive)
/// **OUTPUT**: I512 value in Q256.256 format
/// **PRECISION**: ~77 correct digits
/// **TABLES**: Uses Q256.256 tables with proper multiplicative decomposition
///
/// **ALGORITHM**:
/// For ln(1 + y) where y ∈ [0, 1):
/// 1. Primary lookup: ln(1 + k/1024) where k = floor(y * 1024)
/// 2. Compute scaled remainder: r1 = (y - k/1024) / (1 + k/1024)
/// 3. Secondary lookup on r1: ln(1 + j/2^20) where j = floor(r1 * 2^20)
/// 4. Compute scaled remainder: r2 = (r1 - j/2^20) / (1 + j/2^20)
/// 5. Tertiary lookup on r2: ln(1 + m/2^30) where m = floor(r2 * 2^30)
/// 6. Taylor series on final remainder
/// 7. Add all: ln(1 + k/1024) + ln(1 + j/2^20) + ln(1 + m/2^30) + taylor(remainder)
#[inline(always)]
#[cfg(any(table_format = "q128_128", table_format = "q256_256"))]
pub fn ln_q256_256_native(x: I512) -> I512 {
    use crate::fixed_point::I1024;

    // Handle domain error
    if x <= I512::zero() {
        return I512::min_value();
    }

    let one_q256 = I512::from_i256(I256::from_i128(1)) << 256;
    if x == one_q256 {
        return I512::zero();
    }

    // Range reduction: x = 2^k × m where m ∈ [1, 2)
    let msb_pos = find_msb_position_i512(&x).unwrap_or(0);
    let k = msb_pos as i128 - 256;

    let m = if k >= 0 {
        x >> (k as usize)
    } else {
        x << ((-k) as usize)
    };

    // k × ln(2) with compensation
    let (ln2_main, ln2_comp) = LN_2_CONSTANT_TIER_5;
    // Compensation: shift in larger type to avoid sign extension, then extract
    let ln2_comp_contribution = {
        let comp_i1024 = I1024::from_i512(I512::from_i256(ln2_comp));
        // comp is scaled by 2^128 in build.rs, shift right by 256 to align with main
        (comp_i1024 >> 256).as_i512()
    };
    let ln2 = ln2_main + ln2_comp_contribution;
    let k_i512 = I512::from_i256(I256::from_i128(k)) << 256;
    let k_ln2 = multiply_i512_q256_256(k_i512, ln2);

    // y = m - 1, where y ∈ [0, 1)
    let y = m - one_q256;
    if y == I512::zero() {
        return k_ln2;
    }

    // =========================================================================
    // STAGE 1: Primary table lookup for ln(1 + k/1024)
    // =========================================================================
    // Extract k_idx from top 10 bits of y (bits 246-255)
    let y_upper = (y >> 128).as_i256().as_u128();  // bits 128-255
    let k_idx = (y_upper >> 118) as usize;  // top 10 bits

    let (t1_main, t1_comp) = LN_PRIMARY_TABLE_TIER_5[k_idx];
    let t1_comp_contribution = (I1024::from_i512(I512::from_i256(t1_comp)) >> 256).as_i512();
    let ln_t1 = t1_main + t1_comp_contribution;

    // Compute divisor: d1 = 1 + k/1024 in Q256.256
    let k_frac = I512::from_i256(I256::from_i128(k_idx as i128)) << 246;  // k/1024 in Q256.256
    let d1 = one_q256 + k_frac;

    // Compute y - k/1024
    let y_minus_k = y - k_frac;

    // Compute r1 = (y - k/1024) / (1 + k/1024)
    // This is the scaled remainder for the next stage
    let r1 = if y_minus_k == I512::zero() || k_idx == 0 {
        y_minus_k  // If y_minus_k is 0 or k_idx is 0, no scaling needed
    } else {
        divide_i512_q256_256(y_minus_k, d1)
    };

    // =========================================================================
    // STAGE 2: Secondary table lookup for ln(1 + j/2^20)
    // =========================================================================
    let r1_upper = (r1 >> 128).as_i256().as_u128();
    // Extract bits 236-245 of r1: the "second 10 bits" for j/2^20 decomposition
    // r1 < 1/1024 = 2^-10, so bits 246-255 are 0; we need the NEXT 10 bits
    let j_idx = ((r1_upper >> 108) & 0x3FF) as usize;

    let (t2_main, t2_comp) = LN_SECONDARY_TABLE_TIER_5[j_idx];
    let t2_comp_contribution = (I1024::from_i512(I512::from_i256(t2_comp)) >> 256).as_i512();
    let ln_t2 = t2_main + t2_comp_contribution;

    // j/2^20 in Q256.256 = j << 236
    let j_frac = I512::from_i256(I256::from_i128(j_idx as i128)) << 236;
    let d2 = one_q256 + j_frac;
    let r1_minus_j = r1 - j_frac;

    let r2 = if r1_minus_j == I512::zero() || j_idx == 0 {
        r1_minus_j
    } else {
        divide_i512_q256_256(r1_minus_j, d2)
    };

    // =========================================================================
    // STAGE 3: Tertiary table lookup for ln(1 + m/2^30)
    // =========================================================================
    let r2_upper = (r2 >> 128).as_i256().as_u128();
    // Extract bits 226-235 of r2: the "third 10 bits" for m/2^30 decomposition
    // r2 < 1/2^20, so bits 236-255 are 0; we need bits 226-235
    let m_idx = ((r2_upper >> 98) & 0x3FF) as usize;

    let (t3_main, t3_comp) = LN_TERTIARY_TABLE_TIER_5[m_idx];
    let t3_comp_contribution = (I1024::from_i512(I512::from_i256(t3_comp)) >> 256).as_i512();
    let ln_t3 = t3_main + t3_comp_contribution;

    // m/2^30 in Q256.256 = m << 226
    let m_frac = I512::from_i256(I256::from_i128(m_idx as i128)) << 226;
    let d3 = one_q256 + m_frac;
    let r2_minus_m = r2 - m_frac;

    let r3 = if r2_minus_m == I512::zero() || m_idx == 0 {
        r2_minus_m
    } else {
        divide_i512_q256_256(r2_minus_m, d3)
    };

    // =========================================================================
    // STAGE 4: Quaternary table lookup for ln(1 + p_idx/2^40)
    // =========================================================================
    let r3_upper = (r3 >> 128).as_i256().as_u128();
    // r3 < 1/2^30, so bits 246-255 are 0; extract NEXT 10 bits (216-225)
    let p_idx = ((r3_upper >> 88) & 0x3FF) as usize;

    let (t4_main, t4_comp) = LN_QUATERNARY_TABLE_TIER_5[p_idx];
    let t4_comp_contribution = (I1024::from_i512(I512::from_i256(t4_comp)) >> 256).as_i512();
    let ln_t4 = t4_main + t4_comp_contribution;

    // p/2^40 in Q256.256 = p << 216
    let p_frac = I512::from_i256(I256::from_i128(p_idx as i128)) << 216;
    let d4 = one_q256 + p_frac;
    let r3_minus_p = r3 - p_frac;

    let r4 = if r3_minus_p == I512::zero() || p_idx == 0 {
        r3_minus_p
    } else {
        divide_i512_q256_256(r3_minus_p, d4)
    };

    // =========================================================================
    // STAGE 5: Taylor series for ln(1 + r4) where |r4| < 2^-40
    // =========================================================================
    let ln_remainder = taylor_series_ln_i512_q256_256(&r4);

    // Combine all parts
    k_ln2 + ln_t1 + ln_t2 + ln_t3 + ln_t4 + ln_remainder
}

/// Q512.512 natural logarithm (Tier 6)
///
/// **INPUT**: I1024 value in Q512.512 format (must be positive)
/// **OUTPUT**: I1024 value in Q512.512 format
/// **PRECISION**: ~154 correct digits (tier N+1 for Q256.256 storage)
/// **TABLES**: Uses Q512.512 tables with proper multiplicative decomposition
///
/// **ALGORITHM**:
/// For ln(1 + y) where y ∈ [0, 1):
/// 1. Primary lookup: ln(1 + k/1024) where k = floor(y * 1024)
/// 2. Compute scaled remainder: r1 = (y - k/1024) / (1 + k/1024)
/// 3. Secondary lookup on r1, tertiary lookup on r2
/// 4. Taylor series on final remainder
/// 5. Add all terms
///
/// **NOTE**: Uses power series for division: 1/(1+x) ≈ 1 - x + x² - x³ + ...
#[cfg(any(table_format = "q256_256", table_format = "q512_512"))]
pub fn ln_q512_512_native(x: I1024) -> I1024 {
    use crate::fixed_point::I2048;

    // Handle domain error
    if x <= I1024::zero() {
        return I1024::min_value();
    }

    let one_q512 = I1024::from_i512(I512::from_i256(I256::from_i128(1))) << 512;
    if x == one_q512 {
        return I1024::zero();
    }

    // Range reduction: x = 2^k × m where m ∈ [1, 2)
    let msb_pos = find_msb_position_i1024(&x).unwrap_or(0);
    let k = msb_pos as i128 - 512;

    let m = if k >= 0 {
        x >> (k as usize)
    } else {
        x << ((-k) as usize)
    };

    // k × ln(2) with compensation
    let (ln2_main, ln2_comp) = LN_2_CONSTANT_TIER_6;
    let ln2_comp_contribution = {
        let comp_i2048 = I2048::from_i1024(I1024::from_i512(ln2_comp));
        (comp_i2048 >> 512).as_i1024()
    };
    let ln2 = ln2_main + ln2_comp_contribution;
    let k_i1024 = I1024::from_i512(I512::from_i256(I256::from_i128(k))) << 512;
    let k_ln2 = multiply_i1024_q512_512(k_i1024, ln2);

    // y = m - 1, where y ∈ [0, 1)
    let y = m - one_q512;
    if y == I1024::zero() {
        return k_ln2;
    }

    // =========================================================================
    // STAGE 1: Primary table lookup for ln(1 + k/1024)
    // =========================================================================
    // Extract k_idx from top 10 bits of y (bits 502-511)
    let y_upper = (y >> 384).as_i512().as_i256().as_u128();  // bits 384-511
    let k_idx = (y_upper >> 118) as usize;  // top 10 bits

    let (t1_main, t1_comp) = LN_PRIMARY_TABLE_TIER_6[k_idx];
    let t1_comp_contribution = (I2048::from_i1024(I1024::from_i512(t1_comp)) >> 512).as_i1024();
    let ln_t1 = t1_main + t1_comp_contribution;

    // Compute k/1024 in Q512.512 and divisor d1 = 1 + k/1024
    let k_frac = I1024::from_i512(I512::from_i256(I256::from_i128(k_idx as i128))) << 502;
    let d1 = one_q512 + k_frac;
    let y_minus_k = y - k_frac;

    // r1 = (y - k/1024) / (1 + k/1024) using proper division
    let r1 = if y_minus_k == I1024::zero() || k_idx == 0 {
        y_minus_k
    } else {
        divide_i1024_q512_512(y_minus_k, d1)
    };

    // =========================================================================
    // STAGE 2: Secondary table lookup for ln(1 + j/2^20)
    // =========================================================================
    let r1_upper = (r1 >> 384).as_i512().as_i256().as_u128();
    // Extract bits 492-501 of r1: the "second 10 bits" for j/2^20 decomposition
    // r1 < 1/1024 = 2^-10, so bits 502-511 are 0; we need the NEXT 10 bits
    let j_idx = ((r1_upper >> 108) & 0x3FF) as usize;

    let (t2_main, t2_comp) = LN_SECONDARY_TABLE_TIER_6[j_idx];
    let t2_comp_contribution = (I2048::from_i1024(I1024::from_i512(t2_comp)) >> 512).as_i1024();
    let ln_t2 = t2_main + t2_comp_contribution;

    let j_frac = I1024::from_i512(I512::from_i256(I256::from_i128(j_idx as i128))) << 492;
    let d2 = one_q512 + j_frac;
    let r1_minus_j = r1 - j_frac;

    let r2 = if r1_minus_j == I1024::zero() || j_idx == 0 {
        r1_minus_j
    } else {
        divide_i1024_q512_512(r1_minus_j, d2)
    };

    // =========================================================================
    // STAGE 3: Tertiary table lookup for ln(1 + m/2^30)
    // =========================================================================
    let r2_upper = (r2 >> 384).as_i512().as_i256().as_u128();
    // Extract bits 482-491 of r2: the "third 10 bits" for m/2^30 decomposition
    // r2 < 1/2^20, so bits 492-511 are 0; we need bits 482-491
    let m_idx = ((r2_upper >> 98) & 0x3FF) as usize;

    let (t3_main, t3_comp) = LN_TERTIARY_TABLE_TIER_6[m_idx];
    let t3_comp_contribution = (I2048::from_i1024(I1024::from_i512(t3_comp)) >> 512).as_i1024();
    let ln_t3 = t3_main + t3_comp_contribution;

    let m_frac = I1024::from_i512(I512::from_i256(I256::from_i128(m_idx as i128))) << 482;
    let d3 = one_q512 + m_frac;
    let r2_minus_m = r2 - m_frac;

    let r3 = if r2_minus_m == I1024::zero() || m_idx == 0 {
        r2_minus_m
    } else {
        divide_i1024_q512_512(r2_minus_m, d3)
    };

    // =========================================================================
    // STAGE 4: Quaternary table lookup for ln(1 + p_idx/2^40)
    // =========================================================================
    let r3_upper = (r3 >> 384).as_i512().as_i256().as_u128();
    // r3 < 1/2^30, so bits 502-511 are 0; extract NEXT 10 bits (472-481)
    let p_idx = ((r3_upper >> 88) & 0x3FF) as usize;

    let (t4_main, t4_comp) = LN_QUATERNARY_TABLE_TIER_6[p_idx];
    let t4_comp_contribution = (I2048::from_i1024(I1024::from_i512(t4_comp)) >> 512).as_i1024();
    let ln_t4 = t4_main + t4_comp_contribution;

    // p/2^40 in Q512.512 = p << 472
    let p_frac = I1024::from_i512(I512::from_i256(I256::from_i128(p_idx as i128))) << 472;
    let d4 = one_q512 + p_frac;
    let r3_minus_p = r3 - p_frac;

    let r4 = if r3_minus_p == I1024::zero() || p_idx == 0 {
        r3_minus_p
    } else {
        divide_i1024_q512_512(r3_minus_p, d4)
    };

    // =========================================================================
    // STAGE 5: Taylor series for ln(1 + r4) where |r4| < 2^-40
    // =========================================================================
    let ln_remainder = taylor_series_ln_i1024_q512_512(&r4);

    // Combine all parts
    k_ln2 + ln_t1 + ln_t2 + ln_t3 + ln_t4 + ln_remainder
}

// ============================================================================
// HELPER MULTIPLICATION FUNCTIONS
// ============================================================================

#[cfg(any(table_format = "q64_64", table_format = "q128_128", table_format = "q32_32", table_format = "q16_16"))]
#[inline(always)]
fn multiply_i256_q128_128(a: I256, b: I256) -> I256 {
    // Handle signed multiplication: mul_to_i512 does UNSIGNED multiplication,
    // so we need to handle signs explicitly (same pattern as multiply_i512_q256_256)
    let a_negative = a < I256::zero();
    let b_negative = b < I256::zero();
    let result_negative = a_negative != b_negative;

    let abs_a = if a_negative { I256::zero() - a } else { a };
    let abs_b = if b_negative { I256::zero() - b } else { b };

    let result_i512 = abs_a.mul_to_i512(abs_b);
    let rounding = I512::from_i256(I256::from_i128(1)) << 127;
    let unsigned_result = ((result_i512 + rounding) >> 128).as_i256();

    if result_negative {
        I256::zero() - unsigned_result
    } else {
        unsigned_result
    }
}

/// Divide two I256 values in Q128.128 format
/// Result = (a / b) in Q128.128
#[inline(always)]
#[cfg(any(table_format = "q64_64", table_format = "q128_128", table_format = "q32_32", table_format = "q16_16"))]
fn divide_i256_q128_128(a: I256, b: I256) -> I256 {
    if b == I256::zero() {
        return I256::zero();
    }
    // To compute a/b in Q128.128:
    // Result = (a << 128) / b
    // But a << 128 would overflow I256, so we upscale to I512
    let a_i512 = I512::from_i256(a) << 128;
    let b_i512 = I512::from_i256(b);
    (a_i512 / b_i512).as_i256()
}

/// Taylor series for ln(1+r) in Q128.128 format
/// ln(1+r) = r - r²/2 + r³/3 - r⁴/4 + ... for |r| < 1
///
/// **INPUT**: r is the scaled remainder after 4-stage table lookup, |r| < 2^-40
/// **OUTPUT**: ln(1+r) in Q128.128 format
/// **PRECISION**: For |r| < 2^-40, 5 terms for 128+ bits (r^5 < 2^-200)
#[cfg(any(table_format = "q64_64", table_format = "q128_128", table_format = "q32_32", table_format = "q16_16"))]
#[inline(always)]
fn taylor_series_ln_i256_q128_128(r: &I256) -> I256 {
    if *r == I256::zero() {
        return I256::zero();
    }

    const TERMS: usize = 5; // |r| < 2^-40 → r^5 < 2^-200, well beyond 128-bit precision

    let mut result = *r; // First term: r
    let mut r_power = *r;

    for n in 2..=TERMS {
        // r^n = r^(n-1) × r
        r_power = multiply_i256_q128_128(r_power, *r);

        // Compute 1/n in Q128.128
        let one_q128 = I256::from_i128(1) << 128;
        let n_i256 = I256::from_i128(n as i128);
        let coef = divide_i256_q128_128(one_q128, n_i256 << 128);

        // term = r^n × (1/n)
        let term = multiply_i256_q128_128(r_power, coef);

        // Apply alternating signs: ln(1+r) = r - r²/2 + r³/3 - r⁴/4 + ...
        if n % 2 == 0 {
            result = result - term;
        } else {
            result = result + term;
        }
    }

    result
}

#[cfg(any(table_format = "q128_128", table_format = "q256_256"))]
#[inline(always)]
fn multiply_i512_q256_256(a: I512, b: I512) -> I512 {
    use crate::fixed_point::I1024;

    // Handle signed multiplication: mul_to_i1024 does unsigned multiplication,
    // so we need to handle signs explicitly
    let a_negative = a < I512::zero();
    let b_negative = b < I512::zero();
    let result_negative = a_negative != b_negative;

    let abs_a = if a_negative { I512::zero() - a } else { a };
    let abs_b = if b_negative { I512::zero() - b } else { b };

    let result_i1024 = abs_a.mul_to_i1024(abs_b);
    let rounding = I1024::from_i512(I512::from_i256(I256::from_i128(1))) << 255;
    let unsigned_result = ((result_i1024 + rounding) >> 256).as_i512();

    if result_negative {
        I512::zero() - unsigned_result
    } else {
        unsigned_result
    }
}

/// Divide two I512 values in Q256.256 format
/// Result = (a / b) in Q256.256
#[inline(always)]
#[cfg(any(table_format = "q128_128", table_format = "q256_256"))]
fn divide_i512_q256_256(a: I512, b: I512) -> I512 {
    use crate::fixed_point::I1024;

    if b == I512::zero() {
        return I512::zero();  // Avoid division by zero
    }

    // To compute a/b in Q256.256:
    // Result = (a << 256) / b
    // But a << 256 would overflow I512, so we upscale to I1024
    let a_i1024 = I1024::from_i512(a) << 256;
    let b_i1024 = I1024::from_i512(b);

    // I1024 / I1024 = I1024, then extract I512 result
    (a_i1024 / b_i1024).as_i512()
}

/// Multiply two I1024 values in Q512.512 format
/// **CRITICAL**: mul_to_i2048 does UNSIGNED multiplication, so we handle signs explicitly.
#[inline(always)]
#[cfg(any(table_format = "q256_256", table_format = "q512_512"))]
pub(crate) fn multiply_i1024_q512_512(a: I1024, b: I1024) -> I1024 {
    use crate::fixed_point::I2048;

    let a_negative = a < I1024::zero();
    let b_negative = b < I1024::zero();
    let result_negative = a_negative != b_negative;

    let abs_a = if a_negative { I1024::zero() - a } else { a };
    let abs_b = if b_negative { I1024::zero() - b } else { b };

    let result_i2048 = abs_a.mul_to_i2048(abs_b);
    // Round: add 0.5 ULP at Q512.512 = bit 511
    let rounding = I2048::from_i128(1) << 511;
    let unsigned_result = ((result_i2048 + rounding) >> 512).as_i1024();

    if result_negative {
        I1024::zero() - unsigned_result
    } else {
        unsigned_result
    }
}

/// Divide two I1024 values in Q512.512 format
/// Result = (a / b) in Q512.512
#[inline(always)]
#[cfg(any(table_format = "q256_256", table_format = "q512_512"))]
fn divide_i1024_q512_512(a: I1024, b: I1024) -> I1024 {
    use crate::fixed_point::I2048;
    use crate::fixed_point::domains::binary_fixed::i2048::i2048_div;

    if b == I1024::zero() {
        return I1024::zero();
    }

    // To compute a/b in Q512.512:
    // Result = (a << 512) / b — upscale to I2048 to avoid overflow
    let a_i2048 = I2048::from_i1024(a) << 512;
    let b_i2048 = I2048::from_i1024(b);
    i2048_div(a_i2048, b_i2048).as_i1024()
}

// ============================================================================
// TAYLOR SERIES FOR SMALL REMAINDERS
// ============================================================================

/// Taylor series for ln(1+r) in Q256.256 format
/// ln(1+r) = r - r²/2 + r³/3 - r⁴/4 + ... for |r| < 1
///
/// **INPUT**: r is the scaled remainder after 3-stage table lookup, |r| < 2^-30
/// **OUTPUT**: ln(1+r) in Q256.256 format
/// **PRECISION**: For |r| < 2^-40, only ~7 terms needed for 77 decimals
///
/// **NOTE**: The table LN_TAYLOR_COEFFICIENTS_TIER_5 stores UNSIGNED coefficients (1/n).
/// Signs are applied here: subtract even terms, add odd terms.
/// This is necessary because I512 multiplication is unsigned.
#[cfg(any(table_format = "q128_128", table_format = "q256_256"))]
#[inline(always)]
fn taylor_series_ln_i512_q256_256(r: &I512) -> I512 {
    use crate::fixed_point::I1024;

    if *r == I512::zero() {
        return I512::zero();
    }

    // For very small r (< 2^-40 after 4-stage reduction), convergence is fast
    // Each term r^n/n decreases by factor of r (< 2^-40) per term
    // For 77 decimals (~256 bits), need 256/40 ≈ 7 terms
    const TERMS: usize = 8;  // Extra margin for safety

    let mut result = *r;  // First term: r (coefficient for n=1 is +1)
    let mut r_power = *r;

    for n in 2..=TERMS {
        // r^n = r^(n-1) × r
        r_power = multiply_i512_q256_256(r_power, *r);

        // Coefficient 1/n from table (UNSIGNED - signs applied below)
        let (coef_main, coef_comp) = LN_TAYLOR_COEFFICIENTS_TIER_5[n];
        let coef_comp_contrib = (I1024::from_i512(I512::from_i256(coef_comp)) >> 256).as_i512();
        let coef = coef_main + coef_comp_contrib;

        // term = r^n × (1/n) -- always positive
        let term = multiply_i512_q256_256(r_power, coef);

        // Apply alternating signs: ln(1+r) = r - r²/2 + r³/3 - r⁴/4 + ...
        // Even n: subtract (−r²/2, −r⁴/4, ...)
        // Odd n: add (+r³/3, +r⁵/5, ...)
        if n % 2 == 0 {
            result = result - term;
        } else {
            result = result + term;
        }

        // Early termination if term becomes negligible
        // For |r| < 2^-30, after 10 terms: |term| < (2^-30)^10 / 10 ≈ 2^-300
        // This is beyond our precision, so we can stop
    }

    result
}

/// Taylor series for ln(1+r) in Q512.512 format
/// ln(1+r) = r - r²/2 + r³/3 - r⁴/4 + ... for |r| < 1
///
/// **INPUT**: r is the scaled remainder after 4-stage table lookup, |r| < 2^-40
/// **OUTPUT**: ln(1+r) in Q512.512 format
/// **PRECISION**: For |r| < 2^-40, only ~13 terms needed for 154 decimals
///
/// **NOTE**: The table LN_TAYLOR_COEFFICIENTS_TIER_6 stores UNSIGNED coefficients (1/n).
/// Signs are applied here: subtract even terms, add odd terms.
/// This is necessary because I1024 multiplication is unsigned.
#[cfg(any(table_format = "q256_256", table_format = "q512_512"))]
#[inline(always)]
fn taylor_series_ln_i1024_q512_512(r: &I1024) -> I1024 {
    use crate::fixed_point::I2048;

    if *r == I1024::zero() {
        return I1024::zero();
    }

    // For |r| < 2^-40 after 4-stage reduction:
    // Each term r^n/n decreases by factor of r (< 2^-40) per term
    // For 154 decimals (~512 bits), need 512/40 ≈ 13 terms
    const TERMS: usize = 14;  // Extra margin for safety

    let mut result = *r;  // First term: r (coefficient for n=1 is +1)
    let mut r_power = *r;

    for n in 2..=TERMS {
        // r^n = r^(n-1) × r
        r_power = (r_power.mul_to_i2048(*r) >> 512).as_i1024();

        // Coefficient 1/n from table (UNSIGNED - signs applied below)
        let (coef_main, coef_comp) = LN_TAYLOR_COEFFICIENTS_TIER_6[n];
        let coef_comp_contrib = (I2048::from_i1024(I1024::from_i512(coef_comp)) >> 512).as_i1024();
        let coef = coef_main + coef_comp_contrib;

        // term = r^n × (1/n) -- always positive
        let term = (r_power.mul_to_i2048(coef) >> 512).as_i1024();

        // Apply alternating signs: ln(1+r) = r - r²/2 + r³/3 - r⁴/4 + ...
        // Even n: subtract (−r²/2, −r⁴/4, ...)
        // Odd n: add (+r³/3, +r⁵/5, ...)
        if n % 2 == 0 {
            result = result - term;
        } else {
            result = result + term;
        }
    }

    result
}

// ============================================================================
// PROFILE-AWARE WRAPPERS
// ============================================================================

// ============================================================================
// SCIENTIFIC PROFILE (Q256.256) - UGOD TIER N+1 WRAPPERS
// ============================================================================
// Storage tier → Compute tier → Downscale
// Q64.64 (i128)    → Q128.128 (I256)  → i128    (tier N+1)
// Q128.128 (I256)  → Q256.256 (I512)  → I256    (tier N+1)
// Q256.256 (I512)  → Q512.512 (I1024) → I512    (tier N+1)

#[cfg(table_format = "q256_256")]
pub fn ln_binary_i128(x: i128) -> i128 {
    if x <= 0 {
        return i128::MIN;
    }
    // UGOD Tier N+1: Q64.64 storage → compute at Q128.128 → downscale
    // Upscale Q64.64 → Q128.128
    let x_q128 = I256::from_i128(x) << 64;
    // Compute at Q128.128 (which internally uses Q256.256 tables in scientific profile)
    let x_q256 = I512::from_i256(x_q128) << 128;
    let result_q256 = ln_q256_256_native(x_q256);
    // Downscale Q256.256 → Q128.128 with rounding (0.5 ULP at Q128.128 = bit 127)
    let rounding_q128 = I512::from_i256(I256::from_i128(1)) << 127;
    let result_q128 = ((result_q256 + rounding_q128) >> 128).as_i256();
    // Downscale Q128.128 → Q64.64 with rounding (0.5 ULP at Q64.64 = bit 63)
    let rounding_q64 = I256::from_i128(1i128 << 63);
    ((result_q128 + rounding_q64) >> 64).as_i128()
}

#[cfg(table_format = "q256_256")]
pub fn ln_binary_i256(x: I256) -> I256 {
    if x <= I256::zero() {
        return I256::min_value();
    }
    // UGOD Tier N+1: Q128.128 storage → compute at Q256.256 → downscale
    let x_q256 = I512::from_i256(x) << 128;
    let result_q256 = ln_q256_256_native(x_q256);
    // Downscale Q256.256 → Q128.128 with rounding (0.5 ULP at Q128.128 = bit 127)
    let rounding = I512::from_i256(I256::from_i128(1)) << 127;
    ((result_q256 + rounding) >> 128).as_i256()
}

#[cfg(table_format = "q256_256")]
pub fn ln_binary_i512(x: I512) -> I512 {
    if x <= I512::zero() {
        return I512::min_value();
    }
    // Tier N+1: compute ln at Q512.512, downscale to Q256.256
    let x_q512 = I1024::from_i512(x) << 256;
    let result_q512 = ln_q512_512_native(x_q512);
    // Downscale Q512.512 → Q256.256 with rounding (0.5 ULP at Q256.256 = bit 255)
    let rounding = I1024::from_i512(I512::from_i256(I256::from_i128(1))) << 255;
    ((result_q512 + rounding) >> 256).as_i512()
}

// For balanced profile (Q128.128), provide wrappers
#[cfg(table_format = "q128_128")]
pub fn ln_binary_i128(x: i128) -> i128 {
    if x <= 0 {
        return i128::MIN;
    }
    let x_q128 = I256::from_i128(x) << 64;
    let result_q128 = ln_q128_128_native(x_q128);
    // Downscale Q128.128 → Q64.64 with rounding (0.5 ULP at Q64.64 = bit 63)
    let rounding = I256::from_i128(1i128 << 63);
    ((result_q128 + rounding) >> 64).as_i128()
}

#[cfg(table_format = "q128_128")]
pub fn ln_binary_i256(x: I256) -> I256 {
    if x <= I256::zero() {
        return I256::min_value();
    }
    // UGOD Tier N+1: Q128.128 storage → compute at Q256.256 → downscale
    let x_q256 = I512::from_i256(x) << 128;
    let result_q256 = ln_q256_256_native(x_q256);
    // Downscale Q256.256 → Q128.128 with rounding (0.5 ULP at Q128.128 = bit 127)
    let rounding = I512::from_i256(I256::from_i128(1)) << 127;
    ((result_q256 + rounding) >> 128).as_i256()
}

#[cfg(table_format = "q128_128")]
pub fn ln_binary_i512(x: I512) -> I512 {
    if x <= I512::zero() {
        return I512::min_value();
    }
    // Tier N+1: compute ln at Q256.256 natively (tables available for all profiles)
    ln_q256_256_native(x)
}

// For performance profile (Q64.64), provide wrappers
#[cfg(table_format = "q64_64")]
pub fn ln_binary_i128(x: i128) -> i128 {
    if x <= 0 {
        return i128::MIN;
    }
    // Tier N+1: compute ln at Q128.128, downscale to Q64.64
    let x_q128 = I256::from_i128(x) << 64;
    let result_q128 = ln_q128_128_native(x_q128);
    // Downscale Q128.128 → Q64.64 with rounding (0.5 ULP at Q64.64 = bit 63)
    let rounding = I256::from_i128(1i128 << 63);
    ((result_q128 + rounding) >> 64).as_i128()
}

#[cfg(table_format = "q64_64")]
pub fn ln_binary_i256(x: I256) -> I256 {
    if x <= I256::zero() {
        return I256::min_value();
    }
    // Tier N+1: compute ln at Q128.128 natively (tables available for all profiles)
    ln_q128_128_native(x)
}

#[cfg(table_format = "q64_64")]
pub fn ln_binary_i512(x: I512) -> I512 {
    if x <= I512::zero() {
        return I512::min_value();
    }
    // Q64.64 profile doesn't support I512 natively, downscale
    let x_q64 = (x >> 192).as_i256().as_i128();
    let result_q64 = ln_q64_64_native(x_q64);
    I512::from_i256(I256::from_i128(result_q64)) << 192
}

/// Wrapper for ln_binary_i1024 - computes ln() at Q512.512 precision
#[cfg(any(table_format = "q256_256", table_format = "q512_512"))]
pub fn ln_binary_i1024(x: I1024) -> I1024 {
    if x <= I1024::zero() {
        return I1024::min_value();
    }
    ln_q512_512_native(x)
}

// ============================================================================
// Q32.32 / Q16.16 PROFILE WRAPPERS (i64 storage)
// ============================================================================

/// ln() for Q32.32 storage (i64) — tier N+1 via Q64.64
///
/// For Q16.16 profile: ComputeStorage = i64, BinaryStorage = i32
/// For Q32.32 profile: BinaryStorage = i64
#[cfg(any(table_format = "q32_32", table_format = "q16_16"))]
pub fn ln_binary_i64(x: i64) -> i64 {
    if x <= 0 {
        return i64::MIN;
    }
    use super::exp_tier_n_plus_1::{upscale_q32_to_q64, downscale_q64_to_q32};
    let x_q64 = upscale_q32_to_q64(x);
    let result_q64 = ln_q64_64_native(x_q64);
    downscale_q64_to_q32(result_q64)
}

/// ln() for Q32.32 profile — i128 is the compute tier (Q64.64)
#[cfg(any(table_format = "q32_32", table_format = "q16_16"))]
pub fn ln_binary_i128(x: i128) -> i128 {
    if x <= 0 {
        return i128::MIN;
    }
    ln_q64_64_native(x)
}

/// ln() for Q32.32 profile — I256 is tier N+1 (Q128.128)
#[cfg(any(table_format = "q32_32", table_format = "q16_16"))]
pub fn ln_binary_i256(x: I256) -> I256 {
    if x <= I256::zero() {
        return I256::min_value();
    }
    // Tier N+1: compute ln at Q128.128 natively
    ln_q128_128_native(x)
}

/// ln() for Q32.32 profile — I512 wrapper
#[cfg(any(table_format = "q32_32", table_format = "q16_16"))]
pub fn ln_binary_i512(x: I512) -> I512 {
    if x <= I512::zero() {
        return I512::min_value();
    }
    // Q32.32 profile doesn't support I512 natively, downscale
    let x_q64 = (x >> 192).as_i256().as_i128();
    let result_q64 = ln_q64_64_native(x_q64);
    I512::from_i256(I256::from_i128(result_q64)) << 192
}
