//! Build-time fractional bit configuration.
//!
//! Generated by `build.rs` from the `GMATH_FRAC_BITS` environment variable.
//! Provides compile-time constants for Q-format arithmetic.
//!
//! **Custom FRAC_BITS**: Currently supported for the `realtime` profile (i32 tier) only.
//! Set `GMATH_FRAC_BITS=24` to get Q8.24 instead of the default Q16.16.
//!
//! Constraint: `2 <= FRAC_BITS <= STORAGE_BITS - 2` (at least 1 integer bit + 1 sign bit).

include!(concat!(env!("OUT_DIR"), "/frac_config.rs"));
